export const wordTranslations = {
  'watashi': 'I',
  'wa': '(topic marker)',
  'anata': 'you',
  'no': '(possessive / question particle)',
  'ka': '(question particle)',
  'sou': 'so',
  'desu': 'is / polite ending',
  'shiteiru': 'doing',
  'iu': 'to say',
  'gakkou': 'school',
  'ni': 'to / in',
  'hito': 'person',
  'ano': 'that',
  'sensei': 'teacher',
  'shiranai': 'don’t know',
  'kakko': 'parenthesis',
  'naka': 'inside / middle',
  'iru': 'to be (animate)',
  'tsukatte': 'use (te-form)',
  'kudasai': 'please',
  'taisetsu': 'important',
  'kanojo': 'she',
  'isha': 'doctor',
  'omae': 'you (rough)',
  'dare': 'who',
  'omoshiroi': 'interesting',
  'hanashi': 'story / talk',
  'ashita': 'tomorrow',
  'ka': '(question)',
  'wakatta': 'understood / got it',
  'yo': '(emphasis particle)',
  'kenkyuu': 'research',
  'mono': 'person / thing',
  'sore': 'that',
  'na': '(modifier / emphasis)',
  'kowai': 'scary',
  'toki': 'time / when',
  'kane': 'money',
  'korosanai': 'don’t kill',
  'de': 'at / in / with',
  'au': 'to meet',
  'heya': 'room',
  'hitsuyou': 'necessary',
  'nai': 'not / none',
  'tsukete': 'take / attach (te-form)',
  'arigatou': 'thank you',
  'gozaimasu': 'polite intensifier',
  'ie': 'house / home',
  'tomodachi': 'friend',
  'kyou': 'today',
  'ii': 'good',
  'kotoshi': 'this year',
  'isogashii': 'busy',
  'arimasu': 'there is / have',
  'baggu': 'bag',
  'motte': 'holding (te-form)',
  'iru': 'to be (animate)',
  'tsunaideta': 'held (hands)',
  'issho': 'together',
  'ikou': 'let’s go',
  'denwa': 'phone',
  'shite': 'do (te-form)',
  'dekiru': 'can do / able to',
  'watashi': 'I',
  'wa': '(topic marker)',
  'anata': 'you',
  'no': '(possessive / question particle)',
  'ka': '(question particle)',
  'sou': 'so',
  'desu': 'is / polite ending',
  'shiteiru': 'doing',
  'iu': 'to say',
  'gakkou': 'school',
  'ni': 'to / in',
  'hito': 'person',
  'ano': 'that',
  'sensei': 'teacher',
  'shiranai': 'don’t know',
  'kakko': 'parenthesis',
  'naka': 'inside / middle',
  'iru': 'to be (animate)',
  'tsukatte': 'use (te-form)',
  'kudasai': 'please',
  'taisetsu': 'important',
  'kanojo': 'she',
  'isha': 'doctor',
  'omae': 'you (rough)',
  'dare': 'who',
  'omoshiroi': 'interesting',
  'hanashi': 'story / talk',
  'ashita': 'tomorrow',
  'wakatta': 'understood / got it',
  'yo': '(emphasis particle)',
  'kenkyuu': 'research',
  'mono': 'thing / person / object',
  'sore': 'that',
  'na': '(modifier / emphasis)',
  'kowai': 'scary',
  'toki': 'time / when',
  'kane': 'money',
  'korosanai': 'don’t kill',
  'de': 'at / in / with',
  'au': 'to meet',
  'heya': 'room',
  'hitsuyou': 'necessary',
  'nai': 'not / none',
  'tsukete': 'take / attach (te-form)',
  'arigatou': 'thank you',
  'gozaimasu': 'polite intensifier',
  'ie': 'house / home',
  'tomodachi': 'friend',
  'kyou': 'today',
  'ii': 'good',
  'kotoshi': 'this year',
  'isogashii': 'busy',
  'arimasu': 'there is / have',
  'baggu': 'bag',
  'motte': 'hold (te-form)',
  'tsunaideta': 'held (hands)',
  'issho': 'together',
  'ikou': 'let’s go',
  'denwa': 'phone / call',
  'shite': 'do (te-form)',
  'dekiru': 'can do',
  'hoka': 'other',
  'doko': 'where',
  'hairu': 'enter',
  'me': 'eye',
  'tojite': 'close (te-form)',
  'tanaka': 'Tanaka (name)',
  'sama': 'honorific (Mr./Mrs.)',
  'juppun': '10 minutes',
  'kuruma': 'car',
  'tokoro': 'place',
  'anta': 'you (casual)',
  'baka': 'idiot / stupid',
  'mou': 'already / again',
  'ichido': 'once / one time',
  'onaji': 'same',
  'ikou': 'let’s go',
  'mondai': 'problem / issue',
  'aru': 'exist (inanimate)',
  'kodomo': 'child',
  'nemutteiru': 'sleeping',
  'ai': 'love',
  'kawaii': 'cute',
  'shinじte': 'believe (stem)',
  'saa': 'well then',
  'sukoshi': 'a little',
  'dake': 'only / just',
  'tabemasu': 'eat (polite)',
  'pasokon': 'computer',
  'tsukau': 'use',
  'subete': 'all / everything',
  'owatta': 'finished / over',
  'sekai': 'world',
  'hiroi': 'wide / spacious',
  'oshiete': 'tell / teach (te-form)',
  'kimi': 'you (casual)',
  'kondo': 'next time',
  'yo': '(emphasis particle)',
  'tsukue': 'desk / table',
  'satou': 'sugar',
  'kouhii': 'coffee',
  'ningen': 'human',
  'fukuzatsu': 'complex',
  'hayaku': 'quickly',
  'nichiyoubi': 'Sunday',
  'taisetsu': 'important',
  'yonda': 'called',
  'sensei': 'teacher',
  'imi': 'meaning',
  'wakaranai': 'don’t understand',
  'kami': 'god',
  'shitte': 'know (te-form)',
  'keisatsu': 'police',
  'yonde': 'call (te-form)',
  'chikara': 'strength / power',
  'misete': 'show (te-form)',
  'haha': 'mother',
  'byouin': 'hospital',
  'tsurete': 'bring (te-form)',
  'kankei': 'relation',
  'samui': 'cold',
  'sugosu': 'spend time',
  'rokuji': 'six o’clock',
  'asa': 'morning'
}
