
export const wordPairs = [
    { finnish: 'on', english: 'is', exampleFI: 'Hän on kotona.', exampleEN: 'He is at home.' },
    { finnish: 'ei', english: 'no', exampleFI: 'Ei, kiitos.', exampleEN: 'No, thank you.' },
    { finnish: 'ja', english: 'and', exampleFI: 'Maito ja leipä.', exampleEN: 'Milk and bread.' },
    { finnish: 'se', english: 'it', exampleFI: 'Se on koira.', exampleEN: 'It is a dog.' },
    { finnish: 'hän', english: 'he/she', exampleFI: 'Hän on ystäväni.', exampleEN: 'He/she is my friend.' },
    { finnish: 'en', english: 'I do not', exampleFI: 'En tiedä.', exampleEN: 'I do not know.' },
    { finnish: 'mitä', english: 'what', exampleFI: 'Mitä tämä on?', exampleEN: 'What is this?' },
    { finnish: 'että', english: 'that', exampleFI: 'Tiedän, että hän tulee.', exampleEN: 'I know that he is coming.' },
    { finnish: 'ole', english: 'be', exampleFI: 'Ole hiljaa.', exampleEN: 'Be quiet.' },
    { finnish: 'olen', english: 'I am', exampleFI: 'Olen väsynyt.', exampleEN: 'I am tired.' },
    { finnish: 'niin', english: 'so', exampleFI: 'Niin se on.', exampleEN: 'So it is.' },
    { finnish: 'oli', english: 'was', exampleFI: 'Hän oli täällä.', exampleEN: 'He was here.' },
    { finnish: 'mutta', english: 'but', exampleFI: 'Haluan mennä, mutta en voi.', exampleEN: 'I want to go, but I cannot.' },
    { finnish: 'vain', english: 'only', exampleFI: 'Haluan vain nukkua.', exampleEN: 'I only want to sleep.' },
    { finnish: 'sen', english: 'its', exampleFI: 'Se on sen paikka.', exampleEN: 'It is its place.' },
    { finnish: 'minä', english: 'I', exampleFI: 'Minä olen täällä.', exampleEN: 'I am here.' },
    { finnish: 'jos', english: 'if', exampleFI: 'Jos hän tulee, menemme.', exampleEN: 'If he comes, we will go.' },
    { finnish: 'nyt', english: 'now', exampleFI: 'Teen sen nyt.', exampleEN: 'I will do it now.' },
    { finnish: 'tämä', english: 'this', exampleFI: 'Tämä on hyvä.', exampleEN: 'This is good.' },
    { finnish: 'sinä', english: 'you', exampleFI: 'Sinä olet ystävä.', exampleEN: 'You are a friend.' },
    { finnish: 'voi', english: 'can', exampleFI: 'Voi olla totta.', exampleEN: 'It can be true.' },
    { finnish: 'olet', english: 'are', exampleFI: 'Olet oikeassa.', exampleEN: 'You are right.' },
    { finnish: 'kun', english: 'when', exampleFI: 'Kun hän tulee, menemme.', exampleEN: 'When he comes, we will go.' },
    { finnish: 'sitä', english: 'it', exampleFI: 'Älä koske sitä.', exampleEN: 'Don’t touch it.' },
    { finnish: 'kuin', english: 'than', exampleFI: 'Se on parempi kuin tämä.', exampleEN: 'It is better than this.' },
    { finnish: 'he', english: 'they', exampleFI: 'He ovat täällä.', exampleEN: 'They are here.' },
    { finnish: 'täällä', english: 'here', exampleFI: 'Olen täällä.', exampleEN: 'I am here.' },
    { finnish: 'hänen', english: 'his/her', exampleFI: 'Se on hänen kirjansa.', exampleEN: 'It is his/her book.' },
    { finnish: 'kaikki', english: 'everything', exampleFI: 'Kaikki on hyvin.', exampleEN: 'Everything is fine.' },
    { finnish: 'minun', english: 'my', exampleFI: 'Tämä on minun taloni.', exampleEN: 'This is my house.' },
    { finnish: 'et', english: 'you do not', exampleFI: 'Et tiedä mitään.', exampleEN: 'You do not know anything.' },
    { finnish: 'olla', english: 'to be', exampleFI: 'Haluan olla onnellinen.', exampleEN: 'I want to be happy.' },
    { finnish: 'hyvä', english: 'good', exampleFI: 'Se on hyvä idea.', exampleEN: 'That is a good idea.' },
    { finnish: 'ovat', english: 'are', exampleFI: 'He ovat ystäviäni.', exampleEN: 'They are my friends.' },
    { finnish: 'minua', english: 'me', exampleFI: 'Älä unohda minua.', exampleEN: 'Don’t forget me.' },
    { finnish: 'sitten', english: 'then', exampleFI: 'Sitten menemme kotiin.', exampleEN: 'Then we will go home.' },
    { finnish: 'onko', english: 'is', exampleFI: 'Onko se totta?', exampleEN: 'Is it true?' },
    { finnish: 'sinua', english: 'you', exampleFI: 'Minä rakastan sinua.', exampleEN: 'I love you.' },
    { finnish: 'miksi', english: 'why', exampleFI: 'Miksi teit sen?', exampleEN: 'Why did you do it?' },
    { finnish: 'miten', english: 'how', exampleFI: 'Miten tämä toimii?', exampleEN: 'How does this work?' },
    { finnish: 'älä', english: 'do not', exampleFI: 'Älä huoli.', exampleEN: 'Do not worry.' },
    { finnish: 'sinun', english: 'your', exampleFI: 'Se on sinun vuorosi.', exampleEN: 'It is your turn.' },
    { finnish: 'kyllä', english: 'yes', exampleFI: 'Kyllä, olen samaa mieltä.', exampleEN: 'Yes, I agree.' },
    { finnish: 'mitään', english: 'anything', exampleFI: 'En tiedä mitään.', exampleEN: 'I do not know anything.' },
    { finnish: 'siitä', english: 'about it', exampleFI: 'Puhutaan siitä myöhemmin.', exampleEN: 'We will talk about it later.' },
    { finnish: 'hänet', english: 'him/her', exampleFI: 'Näin hänet eilen.', exampleEN: 'I saw him/her yesterday.' },
    { finnish: 'kiitos', english: 'thank you', exampleFI: 'Kiitos avustasi.', exampleEN: 'Thank you for your help.' },
    { finnish: 'hei', english: 'hello', exampleFI: 'Hei, miten menee?', exampleEN: 'Hello, how are you?' },
    { finnish: 'mikä', english: 'what', exampleFI: 'Mikä tämä on?', exampleEN: 'What is this?' },
    { finnish: 'ne', english: 'they', exampleFI: 'Ne ovat hyviä.', exampleEN: 'They are good.' },
    { finnish: 'olisi', english: 'would be', exampleFI: 'Se olisi mukavaa.', exampleEN: 'That would be nice.' },
    { finnish: 'kanssa', english: 'with', exampleFI: 'Tulen sinun kanssa.', exampleEN: 'I will come with you.' },
    { finnish: 'joka', english: 'every', exampleFI: 'Joka päivä on uusi mahdollisuus.', exampleEN: 'Every day is a new opportunity.' },
    { finnish: 'pitää', english: 'like', exampleFI: 'Minä pidän siitä.', exampleEN: 'I like it.' },
    { finnish: 'ollut', english: 'been', exampleFI: 'Olen ollut täällä aiemmin.', exampleEN: 'I have been here before.' },
    { finnish: 'tässä', english: 'here', exampleFI: 'Tässä on sinun kirjasi.', exampleEN: 'Here is your book.' },
    { finnish: 'tai', english: 'or', exampleFI: 'Otatko kahvia tai teetä?', exampleEN: 'Will you have coffee or tea?' },
    { finnish: 'häntä', english: 'him/her', exampleFI: 'Näin häntä eilen.', exampleEN: 'I saw him/her yesterday.' },
    { finnish: 'minulle', english: 'for me', exampleFI: 'Tämä on minulle.', exampleEN: 'This is for me.' },
    { finnish: 'tiedä', english: 'know', exampleFI: 'En tiedä vastausta.', exampleEN: 'I do not know the answer.' },
    { finnish: 'minulla', english: 'I have', exampleFI: 'Minulla on koira.', exampleEN: 'I have a dog.' },
    { finnish: 'jotain', english: 'something', exampleFI: 'Haluan tehdä jotain uutta.', exampleEN: 'I want to do something new.' },
    { finnish: 'missä', english: 'where', exampleFI: 'Missä olet?', exampleEN: 'Where are you?' },
    { finnish: 'tuo', english: 'that', exampleFI: 'Tuo on minun taloni.', exampleEN: 'That is my house.' },
    { finnish: 'minut', english: 'me', exampleFI: 'Hän näki minut.', exampleEN: 'He saw me.' },
    { finnish: 'me', english: 'we', exampleFI: 'Me olemme ystäviä.', exampleEN: 'We are friends.' },
    { finnish: 'ehkä', english: 'maybe', exampleFI: 'Ehkä menemme huomenna.', exampleEN: 'Maybe we will go tomorrow.' },
    { finnish: 'oletko', english: 'are you', exampleFI: 'Oletko valmis?', exampleEN: 'Are you ready?' },
    { finnish: 'hyvin', english: 'well', exampleFI: 'Kaikki meni hyvin.', exampleEN: 'Everything went well.' },
    { finnish: 'vielä', english: 'still', exampleFI: 'Olen vielä täällä.', exampleEN: 'I am still here.' },
    { finnish: 'kuka', english: 'who', exampleFI: 'Kuka sinä olet?', exampleEN: 'Who are you?' },
    { finnish: 'anteeksi', english: 'sorry', exampleFI: 'Anteeksi, myöhästyin.', exampleEN: 'Sorry, I am late.' },
    { finnish: 'sinulle', english: 'for you', exampleFI: 'Tämä on sinulle.', exampleEN: 'This is for you.' },
    { finnish: 'jo', english: 'already', exampleFI: 'Olen jo valmis.', exampleEN: 'I am already ready.' },
    { finnish: 'sinut', english: 'you', exampleFI: 'Näin sinut eilen.', exampleEN: 'I saw you yesterday.' },
    { finnish: 'tämän', english: 'this', exampleFI: 'Pidän tästä kirjasta.', exampleEN: 'I like this book.' },
    { finnish: 'haluan', english: 'I want', exampleFI: 'Haluan mennä kotiin.', exampleEN: 'I want to go home.' },
    { finnish: 'tänne', english: 'here', exampleFI: 'Tule tänne.', exampleEN: 'Come here.' },
    { finnish: 'koska', english: 'because', exampleFI: 'En mennyt, koska olin väsynyt.', exampleEN: 'I didn’t go because I was tired.' },
    { finnish: 'olemme', english: 'we are', exampleFI: 'Olemme ystäviä.', exampleEN: 'We are friends.' },
    { finnish: 'tehdä', english: 'to do', exampleFI: 'Haluan tehdä jotain hauskaa.', exampleEN: 'I want to do something fun.' },
    { finnish: 'meidän', english: 'our', exampleFI: 'Tämä on meidän koti.', exampleEN: 'This is our home.' },
    { finnish: 'tiedän', english: 'I know', exampleFI: 'Tiedän vastauksen.', exampleEN: 'I know the answer.' },
    { finnish: 'tule', english: 'come', exampleFI: 'Tule tänne.', exampleEN: 'Come here.' },
    { finnish: 'emme', english: 'we do not', exampleFI: 'Emme tiedä vielä.', exampleEN: 'We do not know yet.' },
    { finnish: 'saa', english: 'get', exampleFI: 'Hän saa palkinnon.', exampleEN: 'He gets a prize.' },
    { finnish: 'paljon', english: 'a lot', exampleFI: 'Minulla on paljon työtä.', exampleEN: 'I have a lot of work.' },
    { finnish: 'anna', english: 'give', exampleFI: 'Anna minulle kynä.', exampleEN: 'Give me a pen.' },
    { finnish: 'siellä', english: 'there', exampleFI: 'Olen siellä viideltä.', exampleEN: 'I will be there at five.' },
    { finnish: 'pois', english: 'away', exampleFI: 'Mene pois.', exampleEN: 'Go away.' },
    { finnish: 'täytyy', english: 'must', exampleFI: 'Sinun täytyy tehdä tämä.', exampleEN: 'You must do this.' },
    { finnish: 'sinulla', english: 'you have', exampleFI: 'Sinulla on aikaa.', exampleEN: 'You have time.' },
    { finnish: 'eivät', english: 'they do not', exampleFI: 'He eivät tiedä.', exampleEN: 'They do not know.' },
    { finnish: 'tätä', english: 'this', exampleFI: 'Tätä kirjaa ei voi lainata.', exampleEN: 'This book cannot be borrowed.' },
    { finnish: 'tulee', english: 'comes', exampleFI: 'Hän tulee kotiin.', exampleEN: 'He comes home.' },
    { finnish: 'ennen', english: 'before', exampleFI: 'Olin täällä ennen sinua.', exampleEN: 'I was here before you.' },
    { finnish: 'aina', english: 'always', exampleFI: 'Olen aina valmis auttamaan.', exampleEN: 'I am always ready to help.' },
    { finnish: 'siinä', english: 'in it', exampleFI: 'Siinä on vika.', exampleEN: 'There is a fault in it.' },
    { finnish: 'herra', english: 'mister', exampleFI: 'Herra Virtanen on täällä.', exampleEN: 'Mr. Virtanen is here.' },
    { finnish: 'takaisin', english: 'back', exampleFI: 'Tulen takaisin huomenna.', exampleEN: 'I will come back tomorrow.' },
    { finnish: 'eikö', english: 'isn’t it', exampleFI: 'Eikö tämä ole hienoa?', exampleEN: 'Isn’t this great?' },
    { finnish: 'enää', english: 'anymore', exampleFI: 'En jaksa enää.', exampleEN: 'I can’t continue anymore.' },
    { finnish: 'te', english: 'you (plural)', exampleFI: 'Te olette ystäviäni.', exampleEN: 'You are my friends.' },
    { finnish: 'selvä', english: 'clear', exampleFI: 'Asia on selvä.', exampleEN: 'The matter is clear.' },
    { finnish: 'mistä', english: 'from where', exampleFI: 'Mistä olet kotoisin?', exampleEN: 'Where are you from?' },
    { finnish: 'yksi', english: 'one', exampleFI: 'Yksi päivä kerrallaan.', exampleEN: 'One day at a time.' },
    { finnish: 'juuri', english: 'just', exampleFI: 'Tulimme juuri.', exampleEN: 'We just arrived.' },
    { finnish: 'näin', english: 'like this', exampleFI: 'Tehdään se näin.', exampleEN: 'Let’s do it like this.' },
    { finnish: 'kuinka', english: 'how', exampleFI: 'Kuinka voit?', exampleEN: 'How are you?' },
    { finnish: 'halua', english: 'desire', exampleFI: 'Minulla on halua oppia.', exampleEN: 'I have the desire to learn.' },
    { finnish: 'pitäisi', english: 'should', exampleFI: 'Sinun pitäisi levätä.', exampleEN: 'You should rest.' },
    { finnish: 'vai', english: 'or', exampleFI: 'Kahvia vai teetä?', exampleEN: 'Coffee or tea?' },
    { finnish: 'koko', english: 'whole', exampleFI: 'Luimme koko kirjan.', exampleEN: 'We read the whole book.' },
    { finnish: 'mennä', english: 'to go', exampleFI: 'Haluan mennä kotiin.', exampleEN: 'I want to go home.' },
    { finnish: 'kaksi', english: 'two', exampleFI: 'Minulla on kaksi koiraa.', exampleEN: 'I have two dogs.' },
    { finnish: 'olin', english: 'I was', exampleFI: 'Olin siellä eilen.', exampleEN: 'I was there yesterday.' },
    { finnish: 'meillä', english: 'we have', exampleFI: 'Meillä on uusi auto.', exampleEN: 'We have a new car.' },
    { finnish: 'joku', english: 'someone', exampleFI: 'Joku koputti oveen.', exampleEN: 'Someone knocked on the door.' },
    { finnish: 'koskaan', english: 'never', exampleFI: 'En ole koskaan nähnyt tätä.', exampleEN: 'I have never seen this.' },
    { finnish: 'hänelle', english: 'to him/her', exampleFI: 'Annoin kirjan hänelle.', exampleEN: 'I gave the book to him/her.' },
    { finnish: 'kai', english: 'probably', exampleFI: 'Kai se on totta.', exampleEN: 'It’s probably true.' },
    { finnish: 'tästä', english: 'from this', exampleFI: 'Aloitetaan tästä.', exampleEN: 'Let’s start from this.' },
    { finnish: 'mies', english: 'man', exampleFI: 'Hän on hyvä mies.', exampleEN: 'He is a good man.' },
    { finnish: 'tietää', english: 'to know', exampleFI: 'Haluan tietää totuuden.', exampleEN: 'I want to know the truth.' },
    { finnish: 'aivan', english: 'absolutely', exampleFI: 'Olet aivan oikeassa.', exampleEN: 'You are absolutely right.' },
    { finnish: 'no', english: 'well', exampleFI: 'No, katsotaanpa.', exampleEN: 'Well, let’s see.' },
    { finnish: 'isä', english: 'father', exampleFI: 'Isä on kotona.', exampleEN: 'Father is at home.' },
    { finnish: 'voin', english: 'I can', exampleFI: 'Voin auttaa sinua.', exampleEN: 'I can help you.' },
    { finnish: 'ihan', english: 'quite', exampleFI: 'Se on ihan hyvä.', exampleEN: 'It’s quite good.' },
    { finnish: 'joten', english: 'so', exampleFI: 'Olen väsynyt, joten menen nukkumaan.', exampleEN: 'I am tired, so I will go to sleep.' },
    { finnish: 'mene', english: 'go', exampleFI: 'Mene kotiin.', exampleEN: 'Go home.' },
    { finnish: 'totta', english: 'true', exampleFI: 'Se on totta.', exampleEN: 'That is true.' },
    { finnish: 'oikein', english: 'correct', exampleFI: 'Teit oikein.', exampleEN: 'You did correctly.' },
    { finnish: 'vähän', english: 'a little', exampleFI: 'Haluan vähän sokeria.', exampleEN: 'I want a little sugar.' },
    { finnish: 'siis', english: 'so', exampleFI: 'Olet siis valmis?', exampleEN: 'So you are ready?' },
    { finnish: 'entä', english: 'and', exampleFI: 'Entä sinä?', exampleEN: 'And you?' },
    { finnish: 'aika', english: 'time', exampleFI: 'Aika kuluu nopeasti.', exampleEN: 'Time passes quickly.' },
    { finnish: 'siihen', english: 'to that', exampleFI: 'Vastaus on siinä.', exampleEN: 'The answer is in that.' },
    { finnish: 'olette', english: 'you are (plural)', exampleFI: 'Te olette ystäviäni.', exampleEN: 'You are my friends.' },
    { finnish: 'kuten', english: 'like', exampleFI: 'Toimi kuten sanoin.', exampleEN: 'Do as I said.' },
    { finnish: 'äiti', english: 'mother', exampleFI: 'Äiti on kotona.', exampleEN: 'Mother is at home.' },
    { finnish: 'hyvää', english: 'good', exampleFI: 'Hyvää huomenta.', exampleEN: 'Good morning.' },
    { finnish: 'teet', english: 'you do', exampleFI: 'Mitä teet?', exampleEN: 'What are you doing?' },
    { finnish: 'edes', english: 'even', exampleFI: 'En saanut edes kahvia.', exampleEN: 'I didn’t even get coffee.' },
    { finnish: 'todella', english: 'really', exampleFI: 'Olen todella iloinen.', exampleEN: 'I am really happy.' },
    { finnish: 'eikä', english: 'nor', exampleFI: 'Hän ei tullut eikä soittanut.', exampleEN: 'He neither came nor called.' },
    { finnish: 'voit', english: 'you can', exampleFI: 'Voitko auttaa minua?', exampleEN: 'Can you help me?' },
    { finnish: 'kukaan', english: 'no one', exampleFI: 'Kukaan ei tiedä.', exampleEN: 'No one knows.' },
    { finnish: 'aikaa', english: 'time', exampleFI: 'Minulla on aikaa.', exampleEN: 'I have time.' },
    { finnish: 'haluat', english: 'you want', exampleFI: 'Mitä haluat tehdä?', exampleEN: 'What do you want to do?' },
    { finnish: 'kunnossa', english: 'in order', exampleFI: 'Kaikki on kunnossa.', exampleEN: 'Everything is in order.' },
    { finnish: 'minusta', english: 'about me', exampleFI: 'Mitä ajattelet minusta?', exampleEN: 'What do you think about me?' },
    { finnish: 'itse', english: 'self', exampleFI: 'Hän teki sen itse.', exampleEN: 'He did it himself.' },
    { finnish: 'vaan', english: 'but', exampleFI: 'Ei tämä, vaan tuo.', exampleEN: 'Not this, but that.' },
    { finnish: 'myös', english: 'also', exampleFI: 'Haluan myös kahvia.', exampleEN: 'I also want coffee.' },
    { finnish: 'mukaan', english: 'according to', exampleFI: 'Suunnitelman mukaan.', exampleEN: 'According to the plan.' },
    { finnish: 'ulos', english: 'out', exampleFI: 'Mene ulos.', exampleEN: 'Go out.' },
    { finnish: 'sillä', english: 'because', exampleFI: 'Hän tuli myöhässä, sillä bussi oli myöhässä.', exampleEN: 'He was late because the bus was late.' },
    { finnish: 'sanoi', english: 'said', exampleFI: 'Hän sanoi sen ääneen.', exampleEN: 'He said it out loud.' },
    { finnish: 'kaiken', english: 'everything', exampleFI: 'Tiedän kaiken.', exampleEN: 'I know everything.' },
    { finnish: 'noin', english: 'about', exampleFI: 'Kello on noin viisi.', exampleEN: 'It’s about five o’clock.' },
    { finnish: 'katso', english: 'look', exampleFI: 'Katso tätä kuvaa.', exampleEN: 'Look at this picture.' },
    { finnish: 'tulla', english: 'to come', exampleFI: 'Haluan tulla mukaan.', exampleEN: 'I want to come along.' },
    { finnish: 'ettei', english: 'so that not', exampleFI: 'Tein sen, ettei kukaan huomaisi.', exampleEN: 'I did it so that no one would notice.' },
    { finnish: 'pidä', english: 'like', exampleFI: 'Pidän tästä.', exampleEN: 'I like this.' },
    { finnish: 'hänellä', english: 'he/she has', exampleFI: 'Hänellä on uusi auto.', exampleEN: 'He/she has a new car.' },
    { finnish: 'taas', english: 'again', exampleFI: 'Tapaamme taas huomenna.', exampleEN: 'We will meet again tomorrow.' },
    { finnish: 'auttaa', english: 'help', exampleFI: 'Voitko auttaa minua?', exampleEN: 'Can you help me?' },
    { finnish: 'päästä', english: 'to get', exampleFI: 'Haluan päästä kotiin.', exampleEN: 'I want to get home.' },
    { finnish: 'jälkeen', english: 'after', exampleFI: 'Tulen sinne jälkeen.', exampleEN: 'I will come after that.' },
    { finnish: 'tänään', english: 'today', exampleFI: 'Tänään on kaunis päivä.', exampleEN: 'Today is a beautiful day.' },
    { finnish: 'etkö', english: 'don’t you', exampleFI: 'Etkö tule mukaan?', exampleEN: 'Aren’t you coming along?' },
    { finnish: 'pahoillani', english: 'sorry', exampleFI: 'Olen pahoillani.', exampleEN: 'I am sorry.' },
    { finnish: 'sinusta', english: 'about you', exampleFI: 'Pidän sinusta.', exampleEN: 'I like you.' },
    { finnish: 'puhua', english: 'to speak', exampleFI: 'Haluan puhua kanssasi.', exampleEN: 'I want to speak with you.' },
    { finnish: 'vaikka', english: 'although', exampleFI: 'Vaikka se on vaikeaa, yritän.', exampleEN: 'Although it is difficult, I will try.' },
    { finnish: 'heidän', english: 'their', exampleFI: 'Heidän talonsa on iso.', exampleEN: 'Their house is big.' },
    { finnish: 'niitä', english: 'them', exampleFI: 'En nähnyt niitä.', exampleEN: 'I didn’t see them.' },
    { finnish: 'kerro', english: 'tell', exampleFI: 'Kerro minulle kaikki.', exampleEN: 'Tell me everything.' },
    { finnish: 'tuli', english: 'came', exampleFI: 'Hän tuli kotiin.', exampleEN: 'He came home.' },
    { finnish: 'liian', english: 'too', exampleFI: 'Se on liian kallis.', exampleEN: 'It is too expensive.' },
    { finnish: 'kotiin', english: 'home', exampleFI: 'Menen kotiin.', exampleEN: 'I am going home.' },
    { finnish: 'teidän', english: 'your (plural)', exampleFI: 'Tämä on teidän talonne.', exampleEN: 'This is your house.' },
    { finnish: 'kiinni', english: 'closed', exampleFI: 'Ovi on kiinni.', exampleEN: 'The door is closed.' },
    { finnish: 'tee', english: 'do', exampleFI: 'Tee se nyt.', exampleEN: 'Do it now.' },
    { finnish: 'näyttää', english: 'show', exampleFI: 'Näytä minulle miten se tehdään.', exampleEN: 'Show me how it’s done.' },
    { finnish: 'meitä', english: 'us', exampleFI: 'He eivät nähneet meitä.', exampleEN: 'They didn’t see us.' },
    { finnish: 'muuta', english: 'other', exampleFI: 'En halua mitään muuta.', exampleEN: 'I don’t want anything else.' },
    { finnish: 'vuotta', english: 'years', exampleFI: 'Olen asunut täällä kaksi vuotta.', exampleEN: 'I have lived here for two years.' },
    { finnish: 'mennään', english: 'let’s go', exampleFI: 'Mennään kotiin.', exampleEN: 'Let’s go home.' },
    { finnish: 'nähdä', english: 'to see', exampleFI: 'Haluan nähdä sen.', exampleEN: 'I want to see it.' },
    { finnish: 'heti', english: 'immediately', exampleFI: 'Tule heti tänne.', exampleEN: 'Come here immediately.' },
    { finnish: 'ilman', english: 'without', exampleFI: 'En voi elää ilman sinua.', exampleEN: 'I cannot live without you.' },
    { finnish: 'nämä', english: 'these', exampleFI: 'Nämä ovat hyviä.', exampleEN: 'These are good.' },
    { finnish: 'haluatko', english: 'do you want', exampleFI: 'Haluatko kahvia?', exampleEN: 'Do you want coffee?' },
    { finnish: 'sinne', english: 'there', exampleFI: 'Haluan mennä sinne.', exampleEN: 'I want to go there.' },
    { finnish: 'saat', english: 'you get', exampleFI: 'Saat palkinnon.', exampleEN: 'You get a prize.' },
    { finnish: 'ette', english: 'you do not (plural)', exampleFI: 'Te ette tiedä mitään.', exampleEN: 'You do not know anything.' },
    { finnish: 'sanoa', english: 'to say', exampleFI: 'Mitä haluat sanoa?', exampleEN: 'What do you want to say?' },
    { finnish: 'tapahtui', english: 'happened', exampleFI: 'Mitä tapahtui eilen?', exampleEN: 'What happened yesterday?' },
    { finnish: 'varmasti', english: 'surely', exampleFI: 'Hän tulee varmasti.', exampleEN: 'He will surely come.' },
    { finnish: 'jotka', english: 'which', exampleFI: 'Nämä ovat ne asiat, jotka haluan.', exampleEN: 'These are the things which I want.' },
    { finnish: 'ota', english: 'take', exampleFI: 'Ota tämä kirja.', exampleEN: 'Take this book.' },
    { finnish: 'kolme', english: 'three', exampleFI: 'Minulla on kolme omenaa.', exampleEN: 'I have three apples.' },
    { finnish: 'antaa', english: 'give', exampleFI: 'Voitko antaa minulle kynän?', exampleEN: 'Can you give me a pen?' },
    { finnish: 'tähän', english: 'to this', exampleFI: 'Laita se tähän.', exampleEN: 'Put it to this.' },
    { finnish: 'tiedät', english: 'you know', exampleFI: 'Tiedätkö vastauksen?', exampleEN: 'Do you know the answer?' },
    { finnish: 'odota', english: 'wait', exampleFI: 'Odota hetki.', exampleEN: 'Wait a moment.' },
    { finnish: 'menee', english: 'goes', exampleFI: 'Hän menee kouluun.', exampleEN: 'He goes to school.' },
    { finnish: 'tarvitse', english: 'need', exampleFI: 'En tarvitse apua.', exampleEN: 'I do not need help.' },
    { finnish: 'teitä', english: 'you (plural)', exampleFI: 'Odotan teitä täällä.', exampleEN: 'I am waiting for you here.' },
    { finnish: 'haluaa', english: 'wants', exampleFI: 'Hän haluaa mennä ulos.', exampleEN: 'He wants to go out.' },
    { finnish: 'pian', english: 'soon', exampleFI: 'Nähdään pian.', exampleEN: 'See you soon.' },
    { finnish: 'kertoa', english: 'to tell', exampleFI: 'Haluan kertoa sinulle jotain.', exampleEN: 'I want to tell you something.' },
    { finnish: 'meidät', english: 'us', exampleFI: 'He näkivät meidät.', exampleEN: 'They saw us.' },
    { finnish: 'nähnyt', english: 'seen', exampleFI: 'En ole nähnyt häntä.', exampleEN: 'I have not seen him.' },
    { finnish: 'saada', english: 'to get', exampleFI: 'Haluan saada uuden työn.', exampleEN: 'I want to get a new job.' },
    { finnish: 'täältä', english: 'from here', exampleFI: 'Lähdemme täältä huomenna.', exampleEN: 'We will leave from here tomorrow.' },
    { finnish: 'teen', english: 'I do', exampleFI: 'Teen sen huomenna.', exampleEN: 'I will do it tomorrow.' },
    { finnish: 'hänestä', english: 'about him/her', exampleFI: 'Puhuin hänestä eilen.', exampleEN: 'I talked about him/her yesterday.' },
    { finnish: 'poika', english: 'boy', exampleFI: 'Poika pelaa jalkapalloa.', exampleEN: 'The boy plays football.' },
    { finnish: 'tehnyt', english: 'done', exampleFI: 'Olen tehnyt läksyt.', exampleEN: 'I have done the homework.' },
    { finnish: 'luoja', english: 'creator', exampleFI: 'Luojan kiitos!', exampleEN: 'Thank goodness!' },
    { finnish: 'sanoin', english: 'I said', exampleFI: 'Sanoin sen eilen.', exampleEN: 'I said it yesterday.' },
    { finnish: 'tekee', english: 'does', exampleFI: 'Hän tekee sen hyvin.', exampleEN: 'He does it well.' },
    { finnish: 'sisään', english: 'inside', exampleFI: 'Mene sisään.', exampleEN: 'Go inside.' },
    { finnish: 'enemmän', english: 'more', exampleFI: 'Haluan enemmän kahvia.', exampleEN: 'I want more coffee.' },
    { finnish: 'vastaan', english: 'against', exampleFI: 'Olen vastaan tätä suunnitelmaa.', exampleEN: 'I am against this plan.' },
    { finnish: 'usko', english: 'believe', exampleFI: 'Usko minua.', exampleEN: 'Believe me.' },
    { finnish: 'heidät', english: 'them', exampleFI: 'Näin heidät eilen.', exampleEN: 'I saw them yesterday.' },
    { finnish: 'käy', english: 'visits', exampleFI: 'Hän käy täällä usein.', exampleEN: 'He visits here often.' },
    { finnish: 'tuolla', english: 'over there', exampleFI: 'Se on tuolla.', exampleEN: 'It is over there.' },
    { finnish: 'asia', english: 'matter', exampleFI: 'Tämä on tärkeä asia.', exampleEN: 'This is an important matter.' },
    { finnish: 'heitä', english: 'them', exampleFI: 'He auttoivat heitä.', exampleEN: 'They helped them.' },
    { finnish: 'meille', english: 'to us', exampleFI: 'Hän kertoi meille kaiken.', exampleEN: 'He told us everything.' },
    { finnish: 'n', english: 'a', exampleFI: 'Ota n hetki aikaa.', exampleEN: 'Take a moment.' },
    { finnish: 'jonka', english: 'which', exampleFI: 'Talo, jonka näit, on minun.', exampleEN: 'The house which you saw is mine.' },
    { finnish: 'varmaan', english: 'probably', exampleFI: 'Se on varmaan totta.', exampleEN: 'It is probably true.' },
    { finnish: 'teille', english: 'to you (plural)', exampleFI: 'Minulla on viesti teille.', exampleEN: 'I have a message for you.' },
    { finnish: 'olit', english: 'you were', exampleFI: 'Olitko siellä eilen?', exampleEN: 'Were you there yesterday?' },
    { finnish: 'takia', english: 'because of', exampleFI: 'Myöhästyin liikenteen takia.', exampleEN: 'I was late because of the traffic.' },
    { finnish: 'sano', english: 'say', exampleFI: 'Sano se uudestaan.', exampleEN: 'Say it again.' },
    { finnish: 'sain', english: 'I got', exampleFI: 'Sain lahjan eilen.', exampleEN: 'I got a gift yesterday.' },
    { finnish: 'olivat', english: 'were', exampleFI: 'He olivat ystäviä.', exampleEN: 'They were friends.' },
    { finnish: 'luulin', english: 'I thought', exampleFI: 'Luulin että tiesin vastauksen.', exampleEN: 'I thought I knew the answer.' },
    { finnish: 'hienoa', english: 'great', exampleFI: 'Tämä on hienoa!', exampleEN: 'This is great!' },
    { finnish: 'ikinä', english: 'ever', exampleFI: 'En ole ikinä nähnyt tätä.', exampleEN: 'I have never seen this.' },
    { finnish: 'voimme', english: 'we can', exampleFI: 'Voimme mennä nyt.', exampleEN: 'We can go now.' },
    { finnish: 'tiedätkö', english: 'do you know', exampleFI: 'Tiedätkö missä se on?', exampleEN: 'Do you know where it is?' },
    { finnish: 'piti', english: 'had to', exampleFI: 'Hän piti lähteä aikaisin.', exampleEN: 'He had to leave early.' },
    { finnish: 'tuon', english: 'that', exampleFI: 'Haluan tuon kirjan.', exampleEN: 'I want that book.' },
    { finnish: 'rakastan', english: 'I love', exampleFI: 'Rakastan sinua.', exampleEN: 'I love you.' },
    { finnish: 'olevan', english: 'being', exampleFI: 'Hän on olevan.', exampleEN: 'He is being.' },
    { finnish: 'varma', english: 'sure', exampleFI: 'Oletko varma?', exampleEN: 'Are you sure?' },
    { finnish: 'kuollut', english: 'dead', exampleFI: 'Hän on kuollut.', exampleEN: 'He is dead.' },
    { finnish: 'joo', english: 'yeah', exampleFI: 'Joo, olen samaa mieltä.', exampleEN: 'Yeah, I agree.' },
    { finnish: 'yhdessä', english: 'together', exampleFI: 'Tehdään tämä yhdessä.', exampleEN: 'Let’s do this together.' },
    { finnish: 'voisi', english: 'could', exampleFI: 'Hän voisi auttaa meitä.', exampleEN: 'He could help us.' },
    { finnish: 'ottaa', english: 'to take', exampleFI: 'Haluan ottaa kuvan.', exampleEN: 'I want to take a picture.' },
    { finnish: 'kerran', english: 'once', exampleFI: 'Kerran viikossa.', exampleEN: 'Once a week.' },
    { finnish: 'mihin', english: 'where', exampleFI: 'Mihin olet menossa?', exampleEN: 'Where are you going?' },
    { finnish: 'juttu', english: 'thing', exampleFI: 'Tämä on mielenkiintoinen juttu.', exampleEN: 'This is an interesting thing.' },
    { finnish: 'tarvitsen', english: 'I need', exampleFI: 'Tarvitsen apua.', exampleEN: 'I need help.' },
    { finnish: 'lähteä', english: 'to leave', exampleFI: 'Haluan lähteä nyt.', exampleEN: 'I want to leave now.' },
    { finnish: 'minne', english: 'where', exampleFI: 'Minne menet?', exampleEN: 'Where are you going?' },
    { finnish: 'yhä', english: 'still', exampleFI: 'Olen yhä täällä.', exampleEN: 'I am still here.' },
    { finnish: 'ajan', english: 'driving', exampleFI: 'Ajan autoa.', exampleEN: 'I am driving a car.' },
    { finnish: 'oikeassa', english: 'right', exampleFI: 'Olet oikeassa.', exampleEN: 'You are right.' },
    { finnish: 'yhtä', english: 'equal', exampleFI: 'Olemme yhtä mieltä.', exampleEN: 'We agree.' },
    { finnish: 'siksi', english: 'therefore', exampleFI: 'Olen väsynyt, siksi menen nukkumaan.', exampleEN: 'I am tired, therefore I will go to sleep.' },
    { finnish: 'tulen', english: 'I will come', exampleFI: 'Tulen sinne huomenna.', exampleEN: 'I will come there tomorrow.' },
    { finnish: 'rouva', english: 'madam', exampleFI: 'Hyvää päivää, rouva Virtanen.', exampleEN: 'Good day, Mrs. Virtanen.' },
    { finnish: 'tyttö', english: 'girl', exampleFI: 'Tyttö leikkii pihalla.', exampleEN: 'The girl is playing in the yard.' },
    { finnish: 'tapahtuu', english: 'happens', exampleFI: 'Mitä täällä tapahtuu?', exampleEN: 'What is happening here?' },
    { finnish: 'hauskaa', english: 'fun', exampleFI: 'Pidä hauskaa!', exampleEN: 'Have fun!' },
    { finnish: 'toinen', english: 'another', exampleFI: 'Haluan toisen kahvin.', exampleEN: 'I want another coffee.' },
    { finnish: 'pidän', english: 'I like', exampleFI: 'Pidän tästä kirjasta.', exampleEN: 'I like this book.' },
    { finnish: 'silloin', english: 'then', exampleFI: 'Silloin oli kesä.', exampleEN: 'It was summer then.' },
    { finnish: 'tappaa', english: 'to kill', exampleFI: 'Hän haluaa tappaa aikaa.', exampleEN: 'He wants to kill time.' },
    { finnish: 'teidät', english: 'you (plural)', exampleFI: 'Näin teidät eilen.', exampleEN: 'I saw you (plural) yesterday.' },
    { finnish: 'nainen', english: 'woman', exampleFI: 'Nainen osti kukkia.', exampleEN: 'The woman bought flowers.' },
    { finnish: 'valmis', english: 'ready', exampleFI: 'Oletko valmis lähtemään?', exampleEN: 'Are you ready to leave?' },
    { finnish: 'rahaa', english: 'money', exampleFI: 'Minulla on rahaa.', exampleEN: 'I have money.' },
    { finnish: 'teillä', english: 'you have (plural)', exampleFI: 'Teillä on kiire.', exampleEN: 'You (plural) are in a hurry.' },
    { finnish: 'kauan', english: 'long', exampleFI: 'Kuinka kauan tämä kestää?', exampleEN: 'How long will this take?' },
    { finnish: 'ihmiset', english: 'people', exampleFI: 'Ihmiset ovat ystävällisiä.', exampleEN: 'People are friendly.' },
    { finnish: 'teki', english: 'did', exampleFI: 'Hän teki sen hyvin.', exampleEN: 'He did it well.' },
    { finnish: 'voinut', english: 'could', exampleFI: 'En voinut auttaa häntä.', exampleEN: 'I could not help him.' },
    { finnish: 'pitänyt', english: 'had kept', exampleFI: 'Olisin pitänyt sen.', exampleEN: 'I would have kept it.' },
    { finnish: 'joskus', english: 'sometimes', exampleFI: 'Joskus käyn täällä.', exampleEN: 'Sometimes I visit here.' },
    { finnish: 'ensin', english: 'first', exampleFI: 'Tee tämä ensin.', exampleEN: 'Do this first.' },
    { finnish: 'olisin', english: 'I would be', exampleFI: 'Olisin iloinen.', exampleEN: 'I would be happy.' },
    { finnish: 'yksin', english: 'alone', exampleFI: 'Olen yksin kotona.', exampleEN: 'I am alone at home.' },
    { finnish: 'kulta', english: 'darling', exampleFI: 'Tule tänne, kulta.', exampleEN: 'Come here, darling.' },
    { finnish: 'enkä', english: 'and I do not', exampleFI: 'En tiedä enkä halua tietää.', exampleEN: 'I do not know and do not want to know.' },
    { finnish: 'tohtori', english: 'doctor', exampleFI: 'Tohtori auttaa sinua.', exampleEN: 'The doctor will help you.' },
    { finnish: 'tuota', english: 'that', exampleFI: 'Katso tuota taloa.', exampleEN: 'Look at that house.' },
    { finnish: 'lopeta', english: 'stop', exampleFI: 'Lopeta tuo!', exampleEN: 'Stop that!' },
    { finnish: 'lisää', english: 'more', exampleFI: 'Haluatko lisää kahvia?', exampleEN: 'Do you want more coffee?' },
    { finnish: 'huomenna', english: 'tomorrow', exampleFI: 'Nähdään huomenna.', exampleEN: 'See you tomorrow.' },
    { finnish: 'menen', english: 'I go', exampleFI: 'Menen nyt kotiin.', exampleEN: 'I go home now.' },
    { finnish: 'apua', english: 'help', exampleFI: 'Tarvitsen apua.', exampleEN: 'I need help.' },
    { finnish: 'päivää', english: 'day', exampleFI: 'Hyvää päivää!', exampleEN: 'Good day!' },
    { finnish: 'päivä', english: 'day', exampleFI: 'Tänään on kaunis päivä.', exampleEN: 'Today is a beautiful day.' },
    { finnish: 'tällä', english: 'with this', exampleFI: 'Tällä autolla menemme.', exampleEN: 'We go with this car.' },
    { finnish: 'meni', english: 'went', exampleFI: 'Hän meni ulos.', exampleEN: 'He went out.' },
    { finnish: 'pari', english: 'couple', exampleFI: 'Ota pari omenaa.', exampleEN: 'Take a couple of apples.' },
    { finnish: 'kyse', english: 'a matter', exampleFI: 'Kyse on ajasta.', exampleEN: 'It is a matter of time.' },
    { finnish: 'kertaa', english: 'times', exampleFI: 'Olen käynyt siellä monta kertaa.', exampleEN: 'I have been there many times.' },
    { finnish: 'oliko', english: 'was it', exampleFI: 'Oliko hän kotona?', exampleEN: 'Was he at home?' },
    { finnish: 'älkää', english: 'don’t (plural)', exampleFI: 'Älkää menkö sinne.', exampleEN: 'Don’t go there.' },
    { finnish: 'tosi', english: 'true', exampleFI: 'Se on tosi.', exampleEN: 'It is true.' },
    { finnish: 'myöhemmin', english: 'later', exampleFI: 'Nähdään myöhemmin.', exampleEN: 'See you later.' },
    { finnish: 'tuntuu', english: 'feels', exampleFI: 'Tuntuu hyvältä.', exampleEN: 'It feels good.' },
    { finnish: 'sai', english: 'got', exampleFI: 'Hän sai lahjan.', exampleEN: 'He got a gift.' },
    { finnish: 'nähdään', english: 'see you', exampleFI: 'Nähdään huomenna.', exampleEN: 'See you tomorrow.' },
    { finnish: 'tavata', english: 'to meet', exampleFI: 'Haluan tavata sinut.', exampleEN: 'I want to meet you.' },
    { finnish: 'niinkö', english: 'really', exampleFI: 'Niinkö ajattelet?', exampleEN: 'Do you really think so?' },
    { finnish: 'odottaa', english: 'to wait', exampleFI: 'Hän odottaa bussia.', exampleEN: 'He is waiting for the bus.' },
    { finnish: 'uusi', english: 'new', exampleFI: 'Tämä on minun uusi talo.', exampleEN: 'This is my new house.' },
    { finnish: 'saanut', english: 'received', exampleFI: 'Olen saanut kirjeen.', exampleEN: 'I have received a letter.' },
    { finnish: 'jotta', english: 'so that', exampleFI: 'Teen sen, jotta voin auttaa.', exampleEN: 'I do it so that I can help.' },
    { finnish: 'sanoit', english: 'you said', exampleFI: 'Mitä sanoit?', exampleEN: 'What did you say?' },
    { finnish: 'milloin', english: 'when', exampleFI: 'Milloin tulet?', exampleEN: 'When are you coming?' },
    { finnish: 'ainoa', english: 'only', exampleFI: 'Olen ainoa lapsi.', exampleEN: 'I am the only child.' },
    { finnish: 'saan', english: 'I get', exampleFI: 'Saan uuden työn.', exampleEN: 'I get a new job.' },
    { finnish: 'jonkun', english: 'someone', exampleFI: 'Näin jonkun ovella.', exampleEN: 'I saw someone at the door.' },
    { finnish: 'alas', english: 'down', exampleFI: 'Tule alas nyt.', exampleEN: 'Come down now.' },
    { finnish: 'minäkin', english: 'me too', exampleFI: 'Minäkin haluan jäätelöä.', exampleEN: 'I want ice cream too.' },
    { finnish: 'halusin', english: 'I wanted', exampleFI: 'Halusin tulla mukaan.', exampleEN: 'I wanted to come along.' },
    { finnish: 'yhden', english: 'one', exampleFI: 'Otan yhden kahvin.', exampleEN: 'I will take one coffee.' },
    { finnish: 'paras', english: 'best', exampleFI: 'Hän on paras ystäväni.', exampleEN: 'He is my best friend.' },
    { finnish: 'sir', english: 'sir', exampleFI: 'Kyllä, sir.', exampleEN: 'Yes, sir.' },
    { finnish: 'vie', english: 'takes', exampleFI: 'Auto vie meidät perille.', exampleEN: 'The car takes us to the destination.' },
    { finnish: 'ylös', english: 'up', exampleFI: 'Mene ylös.', exampleEN: 'Go up.' },
    { finnish: 'etten', english: 'that I do not', exampleFI: 'Pelkäsin, etten löydä sitä.', exampleEN: 'I was afraid that I would not find it.' },
    { finnish: 'parempi', english: 'better', exampleFI: 'Tämä on parempi vaihtoehto.', exampleEN: 'This is a better option.' },
    { finnish: 'kuuluu', english: 'belongs', exampleFI: 'Tämä kuuluu minulle.', exampleEN: 'This belongs to me.' },
    { finnish: 'osaa', english: 'knows', exampleFI: 'Hän osaa puhua suomea.', exampleEN: 'He knows how to speak Finnish.' },
    { finnish: 'asiaa', english: 'matter', exampleFI: 'Meillä on tärkeää asiaa.', exampleEN: 'We have an important matter.' },
    { finnish: 'mikään', english: 'nothing', exampleFI: 'Mikään ei toimi.', exampleEN: 'Nothing works.' },
    { finnish: 'silti', english: 'still', exampleFI: 'Olen silti iloinen.', exampleEN: 'I am still happy.' },
    { finnish: 'okei', english: 'okay', exampleFI: 'Okei, tehdään niin.', exampleEN: 'Okay, let’s do that.' },
    { finnish: 'jotakin', english: 'something', exampleFI: 'Haluan jotakin syötävää.', exampleEN: 'I want something to eat.' },
    { finnish: 'paikka', english: 'place', exampleFI: 'Tämä on kaunis paikka.', exampleEN: 'This is a beautiful place.' },
    { finnish: 'ketään', english: 'anyone', exampleFI: 'En nähnyt ketään.', exampleEN: 'I didn’t see anyone.' },
    { finnish: 'viime', english: 'last', exampleFI: 'Viime viikolla olin lomalla.', exampleEN: 'Last week I was on vacation.' },
    { finnish: 'ajattelin', english: 'I thought', exampleFI: 'Ajattelin häntä eilen.', exampleEN: 'I thought of him yesterday.' },
    { finnish: 'jota', english: 'whom', exampleFI: 'Se on nainen, jota rakastan.', exampleEN: 'She is the woman whom I love.' },
    { finnish: 'miehen', english: 'man’s', exampleFI: 'Miehen nimi on Matti.', exampleEN: 'The man’s name is Matti.' },
    { finnish: 'ihmisiä', english: 'people', exampleFI: 'Täällä on paljon ihmisiä.', exampleEN: 'There are many people here.' },
    { finnish: 'alkaa', english: 'to start', exampleFI: 'Haluan alkaa nyt.', exampleEN: 'I want to start now.' },
    { finnish: 'tein', english: 'I did', exampleFI: 'Tein sen eilen.', exampleEN: 'I did it yesterday.' },
    { finnish: 'ymmärrä', english: 'understand', exampleFI: 'En ymmärrä tätä.', exampleEN: 'I do not understand this.' },
    { finnish: 'teit', english: 'you did', exampleFI: 'Mitä teit eilen?', exampleEN: 'What did you do yesterday?' },
    { finnish: 'hieman', english: 'a little', exampleFI: 'Haluan hieman sokeria.', exampleEN: 'I want a little sugar.' },
    { finnish: 'oletteko', english: 'are you (plural)', exampleFI: 'Oletteko valmiit?', exampleEN: 'Are you ready?' },
    { finnish: 'hetki', english: 'moment', exampleFI: 'Odota hetki.', exampleEN: 'Wait a moment.' },
    { finnish: 'kuuntele', english: 'listen', exampleFI: 'Kuuntele musiikkia.', exampleEN: 'Listen to the music.' },
    { finnish: 'muista', english: 'remember', exampleFI: 'Muista ottaa avaimet.', exampleEN: 'Remember to take the keys.' },
    { finnish: 'ohi', english: 'over', exampleFI: 'Koe on ohi.', exampleEN: 'The test is over.' },
    { finnish: 'pieni', english: 'small', exampleFI: 'Tämä on pieni talo.', exampleEN: 'This is a small house.' },
    { finnish: 'yli', english: 'over', exampleFI: 'Hän hyppäsi aidan yli.', exampleEN: 'He jumped over the fence.' },
    { finnish: 'ymmärrän', english: 'I understand', exampleFI: 'Ymmärrän sinua.', exampleEN: 'I understand you.' },
    { finnish: 'tullut', english: 'has come', exampleFI: 'Hän on tullut kotiin.', exampleEN: 'He has come home.' },
    { finnish: 'sama', english: 'same', exampleFI: 'Meillä on sama ongelma.', exampleEN: 'We have the same problem.' },
    { finnish: 'oikea', english: 'right', exampleFI: 'Tämä on oikea vastaus.', exampleEN: 'This is the right answer.' },
    { finnish: 'yritän', english: 'I try', exampleFI: 'Yritän parhaani.', exampleEN: 'I try my best.' },
    { finnish: 'neiti', english: 'miss', exampleFI: 'Hyvää päivää, neiti!', exampleEN: 'Good day, miss!' },
    { finnish: 'riittää', english: 'enough', exampleFI: 'Tämä riittää minulle.', exampleEN: 'This is enough for me.' },
    { finnish: 'vanha', english: 'old', exampleFI: 'Tämä on vanha talo.', exampleEN: 'This is an old house.' },
    { finnish: 'minkä', english: 'which', exampleFI: 'Minkä kirjan haluat?', exampleEN: 'Which book do you want?' },
    { finnish: 'luulen', english: 'I think', exampleFI: 'Luulen, että tiedän vastauksen.', exampleEN: 'I think I know the answer.' },
    { finnish: 'saanko', english: 'may I get', exampleFI: 'Saanko vettä?', exampleEN: 'May I get some water?' },
    { finnish: 'haluaisin', english: 'I would like', exampleFI: 'Haluaisin kahvia.', exampleEN: 'I would like some coffee.' },
    { finnish: 'tiennyt', english: 'knew', exampleFI: 'En tiennyt sitä.', exampleEN: 'I didn’t know that.' },
    { finnish: 'tulin', english: 'I came', exampleFI: 'Tulin kotiin myöhään.', exampleEN: 'I came home late.' },
    { finnish: 'toivottavasti', english: 'hopefully', exampleFI: 'Toivottavasti sää paranee.', exampleEN: 'Hopefully, the weather will improve.' },
    { finnish: 'pyydän', english: 'I ask', exampleFI: 'Pyydän apua.', exampleEN: 'I ask for help.' },
    { finnish: 'voisin', english: 'I could', exampleFI: 'Voisin auttaa sinua.', exampleEN: 'I could help you.' },
    { finnish: 'otan', english: 'I take', exampleFI: 'Otan yhden kahvin.', exampleEN: 'I take one coffee.' },
    { finnish: 'soittaa', english: 'to call', exampleFI: 'Haluan soittaa hänelle.', exampleEN: 'I want to call him.' },
    { finnish: 'kanssasi', english: 'with you', exampleFI: 'Haluan puhua kanssasi.', exampleEN: 'I want to talk with you.' },
    { finnish: 'muuten', english: 'otherwise', exampleFI: 'Tule, muuten myöhästyt.', exampleEN: 'Come, otherwise you will be late.' },
    { finnish: 'jokin', english: 'something', exampleFI: 'Jokin on vialla.', exampleEN: 'Something is wrong.' },
    { finnish: 'isäni', english: 'my father', exampleFI: 'Isäni on kotona.', exampleEN: 'My father is at home.' },
    { finnish: 'teemme', english: 'we do', exampleFI: 'Teemme sen yhdessä.', exampleEN: 'We will do it together.' },
    { finnish: 'voinko', english: 'can I', exampleFI: 'Voinko auttaa sinua?', exampleEN: 'Can I help you?' },
    { finnish: 'kuoli', english: 'died', exampleFI: 'Hän kuoli eilen.', exampleEN: 'He died yesterday.' },
    { finnish: 'tarkoittaa', english: 'to mean', exampleFI: 'Mitä tämä tarkoittaa?', exampleEN: 'What does this mean?' },
    { finnish: 'nopeasti', english: 'quickly', exampleFI: 'Tee se nopeasti.', exampleEN: 'Do it quickly.' },
    { finnish: 'asioita', english: 'things', exampleFI: 'Meillä on paljon asioita tehtävänä.', exampleEN: 'We have many things to do.' },
    { finnish: 'tulkaa', english: 'come (plural)', exampleFI: 'Tulkaa sisään.', exampleEN: 'Come inside.' },
    { finnish: 'puhu', english: 'speak', exampleFI: 'Puhu minulle.', exampleEN: 'Speak to me.' },
    { finnish: 'minuun', english: 'to me', exampleFI: 'Kerro minuun.', exampleEN: 'Tell me.' },
    { finnish: 'tarpeeksi', english: 'enough', exampleFI: 'Olen saanut tarpeeksi.', exampleEN: 'I’ve had enough.' },
    { finnish: 'irti', english: 'off', exampleFI: 'Ota kätesi irti.', exampleEN: 'Take your hand off.' },
    { finnish: 'läpi', english: 'through', exampleFI: 'Kävele oven läpi.', exampleEN: 'Walk through the door.' },
    { finnish: 'hyvältä', english: 'good', exampleFI: 'Tämä maistuu hyvältä.', exampleEN: 'This tastes good.' },
    { finnish: 'kohta', english: 'soon', exampleFI: 'Tulen kohta.', exampleEN: 'I will come soon.' },
    { finnish: 'poissa', english: 'away', exampleFI: 'Hän on poissa tänään.', exampleEN: 'He is away today.' },
    { finnish: 'iso', english: 'big', exampleFI: 'Tämä on iso talo.', exampleEN: 'This is a big house.' },
    { finnish: 'töitä', english: 'work', exampleFI: 'Minulla on paljon töitä.', exampleEN: 'I have a lot of work.' },
    { finnish: 'vasta', english: 'just', exampleFI: 'Tulin vasta nyt.', exampleEN: 'I just arrived now.' },
    { finnish: 'kiltti', english: 'kind', exampleFI: 'Ole kiltti ja auta minua.', exampleEN: 'Be kind and help me.' },
    { finnish: 'nimi', english: 'name', exampleFI: 'Mikä sinun nimesi on?', exampleEN: 'What is your name?' },
    { finnish: 'täysin', english: 'completely', exampleFI: 'Olen täysin samaa mieltä.', exampleEN: 'I completely agree.' },
    { finnish: 'kunnes', english: 'until', exampleFI: 'Odota kunnes palaan.', exampleEN: 'Wait until I return.' },
    { finnish: 'hiljaa', english: 'quietly', exampleFI: 'Puhu hiljaa, ole kiltti.', exampleEN: 'Speak quietly, please.' },
    { finnish: 'poliisi', english: 'police', exampleFI: 'Poliisi saapui nopeasti.', exampleEN: 'The police arrived quickly.' },
    { finnish: 'viisi', english: 'five', exampleFI: 'Minulla on viisi kirjaa.', exampleEN: 'I have five books.' },
    { finnish: 'jossa', english: 'in which', exampleFI: 'Talo, jossa asun, on kaunis.', exampleEN: 'The house in which I live is beautiful.' },
    { finnish: 'olisit', english: 'you would', exampleFI: 'Olisit voinut auttaa.', exampleEN: 'You would have been able to help.' },
    { finnish: 'halunnut', english: 'wanted', exampleFI: 'Olisin halunnut nähdä sen.', exampleEN: 'I would have wanted to see it.' },
    { finnish: 'heille', english: 'for them', exampleFI: 'Annoin kirjan heille.', exampleEN: 'I gave the book to them.' },
    { finnish: 'tahansa', english: 'any', exampleFI: 'Voit valita minkä tahansa.', exampleEN: 'You can choose any.' },
    { finnish: 'asti', english: 'until', exampleFI: 'Odota tähän asti.', exampleEN: 'Wait until this point.' },
    { finnish: 'ettet', english: 'that you do not', exampleFI: 'Pelkäsin, ettet tule.', exampleEN: 'I was afraid that you would not come.' },
    { finnish: 'kaunis', english: 'beautiful', exampleFI: 'Tämä on kaunis päivä.', exampleEN: 'This is a beautiful day.' },
    { finnish: 'senkin', english: 'you', exampleFI: 'Senkin hölmö!', exampleEN: 'You fool!' },
    { finnish: 'tulossa', english: 'coming', exampleFI: 'Olen tulossa kotiin.', exampleEN: 'I am coming home.' },
    { finnish: 'löytää', english: 'to find', exampleFI: 'Haluan löytää ratkaisun.', exampleEN: 'I want to find a solution.' },
    { finnish: 'isäsi', english: 'your father', exampleFI: 'Missä isäsi on?', exampleEN: 'Where is your father?' },
    { finnish: 'käyttää', english: 'to use', exampleFI: 'Osaatko käyttää tätä konetta?', exampleEN: 'Do you know how to use this machine?' },
    { finnish: 'kuitenkin', english: 'however', exampleFI: 'Se on kuitenkin totta.', exampleEN: 'It is true, however.' },
    { finnish: 'oikeasti', english: 'really', exampleFI: 'Oletko oikeasti vakavissasi?', exampleEN: 'Are you really serious?' },
    { finnish: 'vuoden', english: 'year', exampleFI: 'Vuoden 2023 talvi oli kylmä.', exampleEN: 'The winter of 2023 was cold.' },
    { finnish: 'ainakin', english: 'at least', exampleFI: 'Ainakin hän yritti.', exampleEN: 'At least he tried.' },
    { finnish: 'mukana', english: 'with', exampleFI: 'Ota minut mukaan.', exampleEN: 'Take me with you.' },
    { finnish: 'rahat', english: 'money', exampleFI: 'Minulla ei ole rahaa.', exampleEN: 'I don’t have money.' },
    { finnish: 'kuulostaa', english: 'sounds like', exampleFI: 'Se kuulostaa hyvältä.', exampleEN: 'It sounds good.' },
    { finnish: 'miltä', english: 'how', exampleFI: 'Miltä se tuntuu?', exampleEN: 'How does it feel?' },
    { finnish: 'pakko', english: 'must', exampleFI: 'Minun on pakko mennä.', exampleEN: 'I must go.' },
    { finnish: 'yrittää', english: 'to try', exampleFI: 'Haluan yrittää uudelleen.', exampleEN: 'I want to try again.' },
    { finnish: 'sellaista', english: 'such', exampleFI: 'En ole nähnyt mitään sellaista.', exampleEN: 'I have never seen anything like that.' },
    { finnish: 'kiva', english: 'nice', exampleFI: 'Se oli kiva yllätys.', exampleEN: 'It was a nice surprise.' },
    { finnish: 'samaa', english: 'the same', exampleFI: 'Olemme samaa mieltä.', exampleEN: 'We agree.' },
    { finnish: 'dollaria', english: 'dollars', exampleFI: 'Se maksaa viisikymmentä dollaria.', exampleEN: 'It costs fifty dollars.' },
    { finnish: 'neljä', english: 'four', exampleFI: 'Minulla on neljä lasta.', exampleEN: 'I have four children.' },
    { finnish: 'kello', english: 'clock', exampleFI: 'Kello on viisi.', exampleEN: 'It is five o’clock.' },
    { finnish: 'pysy', english: 'stay', exampleFI: 'Pysy siinä.', exampleEN: 'Stay there.' },
    { finnish: 'paska', english: 'crap', exampleFI: 'Tämä on ihan paska tilanne.', exampleEN: 'This is a crappy situation.' },
    { finnish: 'ensimmäinen', english: 'first', exampleFI: 'Hän on ensimmäinen asiakas.', exampleEN: 'He is the first customer.' },
    { finnish: 'kaveri', english: 'friend', exampleFI: 'Hän on hyvä kaveri.', exampleEN: 'He is a good friend.' },
    { finnish: 'mukava', english: 'pleasant', exampleFI: 'Ilma on mukava.', exampleEN: 'The weather is pleasant.' },
    { finnish: 'sanoo', english: 'says', exampleFI: 'Hän sanoo sen usein.', exampleEN: 'He says it often.' },
    { finnish: 'kotona', english: 'at home', exampleFI: 'Olen kotona.', exampleEN: 'I am at home.' },
    { finnish: 'tunnen', english: 'I feel', exampleFI: 'Tunnen oloni hyväksi.', exampleEN: 'I feel good.' },
    { finnish: 'tarkoitat', english: 'you mean', exampleFI: 'Mitä tarkoitat?', exampleEN: 'What do you mean?' },
    { finnish: 'liikaa', english: 'too much', exampleFI: 'Tämä on liikaa.', exampleEN: 'This is too much.' },
    { finnish: 'hitto', english: 'damn', exampleFI: 'Hitto, unohdin sen!', exampleEN: 'Damn, I forgot it!' },
    { finnish: 'kuulin', english: 'I heard', exampleFI: 'Kuulin sen uutisista.', exampleEN: 'I heard it on the news.' },
    { finnish: 'mieltä', english: 'mind', exampleFI: 'Mitä mieltä olet?', exampleEN: 'What do you think?' },
    { finnish: 'melkein', english: 'almost', exampleFI: 'Olen melkein valmis.', exampleEN: 'I am almost ready.' },
    { finnish: 'näytä', english: 'show', exampleFI: 'Näytä minulle.', exampleEN: 'Show me.' },
    { finnish: 'niistä', english: 'about them', exampleFI: 'Puhutaan niistä myöhemmin.', exampleEN: 'We’ll talk about them later.' },
    { finnish: 'kerron', english: 'I will tell', exampleFI: 'Kerron sinulle huomenna.', exampleEN: 'I will tell you tomorrow.' },
    { finnish: 'kuullut', english: 'heard', exampleFI: 'Oletko kuullut sen?', exampleEN: 'Have you heard it?' },
    { finnish: 'eilen', english: 'yesterday', exampleFI: 'Näin hänet eilen.', exampleEN: 'I saw him yesterday.' },
    { finnish: 'varten', english: 'for', exampleFI: 'Tämä on sinua varten.', exampleEN: 'This is for you.' },
    { finnish: 'hieno', english: 'fine', exampleFI: 'Se oli hieno kokemus.', exampleEN: 'It was a fine experience.' },
    { finnish: 'muut', english: 'others', exampleFI: 'Muut ovat jo täällä.', exampleEN: 'The others are already here.' },
    { finnish: 'tunne', english: 'feeling', exampleFI: 'Minulla on hyvä tunne tästä.', exampleEN: 'I have a good feeling about this.' },
    { finnish: 'siltä', english: 'feels like', exampleFI: 'Tuntuu siltä, että tämä onnistuu.', exampleEN: 'It feels like this will work.' },
    { finnish: 'mä', english: 'I (informal)', exampleFI: 'Mä menen nyt.', exampleEN: 'I’m going now.' },
    { finnish: 'asian', english: 'matter', exampleFI: 'Tämä on tärkeä asia.', exampleEN: 'This is an important matter.' },
    { finnish: 'sait', english: 'you got', exampleFI: 'Saitko kirjeen?', exampleEN: 'Did you get the letter?' },
    { finnish: 'kuulla', english: 'to hear', exampleFI: 'Haluan kuulla sen.', exampleEN: 'I want to hear it.' },
    { finnish: 'näen', english: 'I see', exampleFI: 'Näen sinut huomenna.', exampleEN: 'I’ll see you tomorrow.' },
    { finnish: 'meistä', english: 'about us', exampleFI: 'Mitä ajattelet meistä?', exampleEN: 'What do you think about us?' },
    { finnish: 'kertonut', english: 'told', exampleFI: 'Olen kertonut sen sinulle.', exampleEN: 'I have told you that.' },
    { finnish: 'eli', english: 'that is', exampleFI: 'Hän on eliittiä.', exampleEN: 'He is an elite.' },
    { finnish: 'luulet', english: 'you think', exampleFI: 'Luuletko niin?', exampleEN: 'Do you think so?' },
    { finnish: 'kapteeni', english: 'captain', exampleFI: 'Kapteeni johtaa alusta.', exampleEN: 'The captain leads the ship.' },
    { finnish: 'john', english: 'John', exampleFI: 'John on ystäväni.', exampleEN: 'John is my friend.' },
    { finnish: 'tänä', english: 'this', exampleFI: 'Tänä iltana menemme ulos.', exampleEN: 'We are going out this evening.' },
    { finnish: 'pysty', english: 'able', exampleFI: 'En pysty tekemään sitä.', exampleEN: 'I am not able to do it.' },
    { finnish: 'hauska', english: 'fun', exampleFI: 'Oli hauska ilta.', exampleEN: 'It was a fun evening.' },
    { finnish: 'haloo', english: 'hello', exampleFI: 'Haloo, oletko siellä?', exampleEN: 'Hello, are you there?' },
    { finnish: 'kertoi', english: 'told', exampleFI: 'Hän kertoi minulle uutiset.', exampleEN: 'He told me the news.' },
    { finnish: 'toisen', english: 'another', exampleFI: 'Haluan toisen mahdollisuuden.', exampleEN: 'I want another chance.' },
    { finnish: 'jumala', english: 'God', exampleFI: 'Jumala on suuri.', exampleEN: 'God is great.' },
    { finnish: 'tehdään', english: 'let’s do', exampleFI: 'Tehdään se yhdessä.', exampleEN: 'Let’s do it together.' },
    { finnish: 'kanssani', english: 'with me', exampleFI: 'Tule kanssani.', exampleEN: 'Come with me.' },
    { finnish: 'auta', english: 'help', exampleFI: 'Auta minua, ole kiltti.', exampleEN: 'Help me, please.' },
    { finnish: 'luuletko', english: 'do you think', exampleFI: 'Luuletko, että se toimii?', exampleEN: 'Do you think it will work?' },
    { finnish: 'pikku', english: 'little', exampleFI: 'Pikkuveli on hauska.', exampleEN: 'Little brother is funny.' },
    { finnish: 'jopa', english: 'even', exampleFI: 'Jopa hän tuli juhliin.', exampleEN: 'Even he came to the party.' },
    { finnish: 'sieltä', english: 'from there', exampleFI: 'Näin sen sieltä.', exampleEN: 'I saw it from there.' },
    { finnish: 'näytät', english: 'you look', exampleFI: 'Näytät väsyneeltä.', exampleEN: 'You look tired.' },
    { finnish: 'paitsi', english: 'except', exampleFI: 'Kaikki tulivat paitsi hän.', exampleEN: 'Everyone came except him.' },
    { finnish: 'nuo', english: 'those', exampleFI: 'Nuokin ovat minun.', exampleEN: 'Those are mine too.' },
    { finnish: 'puhut', english: 'you speak', exampleFI: 'Puhut hyvin suomea.', exampleEN: 'You speak Finnish well.' },
    { finnish: 'uskoa', english: 'to believe', exampleFI: 'Haluan uskoa sinua.', exampleEN: 'I want to believe you.' },
    { finnish: 'äitisi', english: 'your mother', exampleFI: 'Missä äitisi on?', exampleEN: 'Where is your mother?' },
    { finnish: 'suoraan', english: 'directly', exampleFI: 'Mene suoraan kotiin.', exampleEN: 'Go directly home.' },
    { finnish: 'voitte', english: 'you can (plural)', exampleFI: 'Voitteko auttaa meitä?', exampleEN: 'Can you help us?' },
    { finnish: 'olimme', english: 'we were', exampleFI: 'Olimme siellä eilen.', exampleEN: 'We were there yesterday.' },
    { finnish: 'kanssaan', english: 'with him/her', exampleFI: 'Olen hänen kanssaan.', exampleEN: 'I am with him/her.' },
    { finnish: 'mikset', english: 'why not', exampleFI: 'Mikset sano sitä?', exampleEN: 'Why don’t you say it?' }
];

export const wordTranslations = {
    'Hän': 'He/She',
    'on': 'is',
    'kotona': 'at home',
    'Ei': 'No',
    'kiitos': 'thank you',
    'Maito': 'Milk',
    'ja': 'and',
    'leipä': 'bread',
    'Se': 'It',
    'koira': 'dog',
    'ystäväni': 'my friend',
    'En': 'I do not',
    'tiedä': 'know',
    'Mitä': 'What',
    'tämä': 'this',
    'Tiedän': 'I know',
    'että': 'that',
    'tulee': 'comes',
    'Ole': 'be',
    'hiljaa': 'quiet',
    'Olen': 'I am',
    'väsynyt': 'tired',
    'oli': 'was',
    'Niin': 'So',
    'Haluan': 'I want',
    'mennä': 'to go',
    'mutta': 'but',
    'sen': 'its',
    'paikka': 'place',
    'vain': 'only',
    'nukkua': 'sleep',
    'Minä': 'I',
    'olen': 'am',
    'Jos': 'If',
    'menemme': 'we will go',
    'hyvä': 'good',
    'Teen': 'I will do',
    'nyt': 'now',
    'Voi': 'can',
    'olla': 'be',
    'totta': 'true',
    'Sinä': 'You',
    'olet': 'are',
    'oikeassa': 'right',
    'Kun': 'When',
    'Älä': 'do not',
    'koske': 'touch',
    'sitä': 'it',
    'parempi': 'better',
    'He': 'They',
    'kirjansa': 'book',
    'Kaikki': 'Everything',
    'on': 'is',
    'hyvin': 'fine',
    'Tämä': 'This',
    'on': 'is',
    'taloni': 'my house',
    'ovat': 'are',
    'ystäväni': 'my friends',
    'unohda': 'forget',
    'Sitten': 'Then',
    'menemme': 'we will go',
    'kotiin': 'home',
    'Onko': 'Is',
    'se': 'it',
    'totta': 'true',
    'Miksi': 'Why',
    'teit': 'did',
    'Minä': 'I',
    'rakastan': 'love',
    'sinua': 'you',
    'Miten': 'How',
    'toimii': 'works',
    'Se': 'It',
    'on': 'is',
    'sinun': 'your',
    'vuorosi': 'turn',
    'Älä': 'Do not',
    'huoli': 'worry',
    'Puhutaan': 'We will talk',
    'siitä': 'about it',
    'myöhemmin': 'later',
    'Näin': 'I saw',
    'hänet': 'him/her',
    'eilen': 'yesterday',
    'En': 'I do not',
    'mitään': 'anything',
    'Kyllä': 'Yes',
    'olen': 'I am',
    'samaa': 'same',
    'mieltä': 'opinion',
    'Kiitos': 'Thank you',
    'avustasi': 'for your help',
    'Hei': 'Hello',
    'miten': 'how',
    'menee': 'goes',
    'Mikä': 'What',
    'tämä': 'this',
    'Ne': 'They',
    'ovat': 'are',
    'hyviä': 'good',
    'Se': 'It',
    'olisi': 'would be',
    'mukavaa': 'nice',
    'Tulen': 'I will come',
    'sinun': 'your',
    'kanssa': 'with',
    'Joka': 'Every',
    'päivä': 'day',
    'uusi': 'new',
    'mahdollisuus': 'opportunity',
    'Olen': 'I am',
    'ollut': 'been',
    'täällä': 'here',
    'aiemmin': 'before',
    'Otatko': 'Will you have',
    'kahvia': 'coffee',
    'tai': 'or',
    'teetä': 'tea',
    'Hän': 'He',
    'näki': 'saw',
    'minut': 'me',
    'Minulle': 'For me',
    'Se': 'It',
    'on': 'is',
    'minulle': 'for me',
    'Tiedä': 'know',
    'Minulla': 'I have',
    'on': 'is',
    'koira': 'dog',
    'Jotain': 'something',
    'haluan': 'I want',
    'tehdä': 'to do',
    'Missä': 'Where',
    'olet': 'are',
    'Tuo': 'That',
    'on': 'is',
    'minun': 'mine',
    'Tule': 'Come',
    'tänne': 'here',
    'Ehkä': 'Maybe',
    'menemme': 'we will go',
    'huomenna': 'tomorrow',
    'Oletko': 'Are you',
    'valmis': 'ready',
    'Hyvin': 'Well',
    'kaikki': 'everything',
    'meni': 'went',
    'Hyvin': 'Well',
    'vielä': 'still',
    'olen': 'I am',
    'täällä': 'here',
    'Kuka': 'Who',
    'sinä': 'you',
    'olet': 'are',
    'Anteeksi': 'Sorry',
    'myöhästyin': 'I am late',
    'Tämä': 'This',
    'on': 'is',
    'sinulle': 'for you',
    'Jo': 'Already',
    'Olen': 'I am',
    'valmis': 'ready',
    'Näin': 'I saw',
    'sinut': 'you',
    'eilen': 'yesterday',
    'Pidän': 'I like',
    'tästä': 'this',
    'kirjasta': 'book',
    'Haluan': 'I want',
    'mennä': 'to go',
    'kotiin': 'home',
    'Koska': 'Because',
    'en': 'I do not',
    'mennyt': 'go',
    'koska': 'because',
    'olin': 'I was',
    'väsynyt': 'tired',
    'Olemme': 'We are',
    'ystävät': 'friends',
    'Tehdä': 'to do',
    'Haluan': 'I want',
    'meidän': 'our',
    'koti': 'home',
    'tiedän': 'I know',
    'tule': 'come',
    'emme': 'we do not',
    'vielä': 'yet',
    'saa': 'gets',
    'palkinnon': 'a prize',
    'minulla': 'I have',
    'aikaa': 'time',
    'anna': 'give',
    'minulle': 'me',
    'Mene': 'Go',
    'pois': 'away',
    'täytyy': 'must',
    'sinun': 'your',
    'tätä': 'this',
    'kirjaa': 'book',
    'Hän': 'He',
    'tulee': 'comes',
    'kotiin': 'home',
    'Olin': 'I was',
    'täällä': 'here',
    'ennen': 'before',
    'Aina': 'Always',
    'valmis': 'ready',
    'auttamaan': 'to help',
    'Herra': 'Mr.',
    'Virtanen': 'Virtanen',
    'Tulen': 'I will come',
    'takaisin': 'back',
    'huomenna': 'tomorrow',
    'Eikö': 'Isn’t it',
    'tämä': 'this',
    'ole': 'is',
    'hienoa': 'great',
    'En': 'I do not',
    'jaksa': 'can’t continue',
    'enää': 'anymore',
    'Te': 'You (plural)',
    'olette': 'are',
    'ystäviäni': 'my friends',
    'Asia': 'The matter',
    'on': 'is',
    'selvä': 'clear',
    'Mistä': 'From where',
    'olet': 'are',
    'kotoisin': 'from',
    'Yksi': 'One',
    'päivä': 'day',
    'kerrallaan': 'at a time',
    'Tulimme': 'We arrived',
    'juuri': 'just',
    'Tehdään': 'Let’s do',
    'se': 'it',
    'näin': 'like this',
    'Kuinka': 'How',
    'voit': 'can',
    'Minulla': 'I have',
    'on': 'is',
    'halua': 'desire',
    'oppia': 'to learn',
    'Sinun': 'Your',
    'pitäisi': 'should',
    'levätä': 'rest',
    'Kahvia': 'Coffee',
    'vai': 'or',
    'teetä': 'tea',
    'Luimme': 'We read',
    'koko': 'whole',
    'kirjan': 'book',
    'Haluan': 'I want',
    'mennä': 'to go',
    'kotiin': 'home',
    'Minulla': 'I have',
    'kaksi': 'two',
    'koiraa': 'dogs',
    'Olin': 'I was',
    'siellä': 'there',
    'eilen': 'yesterday',
    'Meillä': 'We have',
    'uusi': 'new',
    'auto': 'car',
    'Joku': 'Someone',
    'koputti': 'knocked',
    'oveen': 'on the door',
    'En': 'I have',
    'ole': 'never',
    'koskaan': 'seen',
    'nähnyt': 'seen',
    'tätä': 'this',
    'Annoin': 'I gave',
    'kirjan': 'book',
    'hänelle': 'to him/her',
    'Kai': 'Probably',
    'se': 'it',
    'on': 'is',
    'totta': 'true',
    'Aloitetaan': 'Let’s start',
    'tästä': 'from this',
    'Hän': 'He',
    'on': 'is',
    'hyvä': 'good',
    'mies': 'man',
    'Haluan': 'I want',
    'tietää': 'to know',
    'totuuden': 'the truth',
    'Olet': 'You are',
    'aivan': 'absolutely',
    'oikeassa': 'right',
    'No': 'Well',
    'katsotaanpa': 'let’s see',
    'Isä': 'Father',
    'on': 'is',
    'kotona': 'at home',
    'Voin': 'I can',
    'auttaa': 'help',
    'sinua': 'you',
    'Se': 'It',
    'on': 'is',
    'ihan': 'quite',
    'hyvä': 'good',
    'Olen': 'I am',
    'väsynyt': 'tired',
    'joten': 'so',
    'menen': 'I will go',
    'nukkumaan': 'to sleep',
    'Mene': 'Go',
    'kotiin': 'home',
    'Totta': 'True',
    'on': 'is',
    'Teit': 'You did',
    'oikein': 'correctly',
    'Haluan': 'I want',
    'vähän': 'a little',
    'sokeria': 'sugar',
    'Olet': 'So',
    'valmis': 'ready',
    'Entä': 'And',
    'sinä': 'you',
    'Aika': 'Time',
    'kuluu': 'passes',
    'nopeasti': 'quickly',
    'Vastaus': 'The answer',
    'on': 'is',
    'siinä': 'in that',
    'Te': 'You (plural)',
    'olette': 'are',
    'ystäviäni': 'my friends',
    'Toimi': 'Do',
    'kuten': 'as',
    'sanoin': 'I said',
    'Äiti': 'Mother',
    'on': 'is',
    'kotona': 'at home',
    'Hyvää': 'Good',
    'huomenta': 'morning',
    'Mitä': 'What',
    'teet': 'are you doing',
    'En': 'I did not',
    'saanut': 'get',
    'edes': 'even',
    'kahvia': 'coffee',
    'Olen': 'I am',
    'todella': 'really',
    'iloinen': 'happy',
    'Hän': 'He',
    'ei': 'did not',
    'tullut': 'come',
    'eikä': 'nor',
    'soittanut': 'call',
    'Voitko': 'Can you',
    'auttaa': 'help',
    'minua': 'me',
    'Kukaan': 'No one',
    'ei': 'does not',
    'tiedä': 'know',
    'Minulla': 'I have',
    'aikaa': 'time',
    'Mitä': 'What',
    'haluat': 'you want',
    'tehdä': 'to do',
    'Kaikki': 'Everything',
    'on': 'is',
    'kunnossa': 'in order',
    'Mitä': 'What',
    'ajattelet': 'do you think',
    'minusta': 'about me',
    'Hän': 'He',
    'teki': 'did',
    'sen': 'it',
    'itse': 'himself',
    'Ei': 'Not',
    'tämä': 'this',
    'vaan': 'but',
    'tuo': 'that',
    'Haluan': 'I also want',
    'myös': 'also',
    'kahvia': 'coffee',
    'Suunnitelman': 'According to',
    'mukaan': 'the plan',
    'Mene': 'Go',
    'ulos': 'out',
    'Hän': 'He',
    'tuli': 'was late',
    'myöhässä': 'because',
    'sillä': 'the bus was late',
    'Hän': 'He',
    'sanoi': 'said',
    'sen': 'it',
    'ääneen': 'out loud',
    'Tiedän': 'I know',
    'kaiken': 'everything',
    'Kello': 'The clock',
    'on': 'is',
    'noin': 'about',
    'viisi': 'five',
    'Katso': 'Look',
    'tätä': 'at this',
    'kuvaa': 'picture',
    'Haluan': 'I want',
    'tulla': 'to come',
    'mukaan': 'along',
    'Tein': 'I did',
    'sen': 'it',
    'ettei': 'so that',
    'kukaan': 'no one',
    'huomaisi': 'would notice',
    'Pidä': 'I like',
    'tästä': 'this',
    'Hänellä': 'He/she has',
    'on': 'is',
    'uusi': 'new',
    'auto': 'car',
    'Tapaamme': 'We will meet',
    'taas': 'again',
    'huomenna': 'tomorrow',
    'Voitko': 'Can you',
    'auttaa': 'help',
    'minua': 'me',
    'Haluan': 'I want',
    'päästä': 'to get',
    'kotiin': 'home',
    'Tulen': 'I will come',
    'jälkeen': 'after that',
    'Tänään': 'Today',
    'on': 'is',
    'kaunis': 'beautiful',
    'päivä': 'day',
    'Etkö': 'Aren’t you',
    'tule': 'coming',
    'mukaan': 'along',
    'Olen': 'I am',
    'pahoillani': 'sorry',
    'Pidän': 'I like',
    'sinusta': 'you',
    'Haluan': 'I want',
    'puhua': 'to speak',
    'kanssasi': 'with you',
    'Vaikka': 'Although',
    'se': 'it',
    'on': 'is',
    'vaikeaa': 'difficult',
    'yritän': 'I will try',
    'Heidän': 'Their',
    'talonsa': 'house',
    'on': 'is',
    'iso': 'big',
    'En': 'I did not',
    'nähnyt': 'see',
    'niitä': 'them',
    'Kerro': 'Tell',
    'minulle': 'me',
    'kaikki': 'everything',
    'Hän': 'He',
    'tuli': 'came',
    'kotiin': 'home',
    'Se': 'It',
    'on': 'is',
    'liian': 'too',
    'kallis': 'expensive',
    'Menen': 'I am going',
    'kotiin': 'home',
    'Tämä': 'This',
    'on': 'is',
    'teidän': 'your (plural)',
    'talonne': 'house',
    'Ovi': 'The door',
    'on': 'is',
    'kiinni': 'closed',
    'Tee': 'Do',
    'se': 'it',
    'nyt': 'now',
    'Näytä': 'Show',
    'minulle': 'me',
    'miten': 'how',
    'se': 'it',
    'tehdään': 'is done',
    'He': 'They',
    'eivät': 'did not',
    'nähneet': 'see',
    'meitä': 'us',
    'En': 'I do not',
    'halua': 'want',
    'mitään': 'anything else',
    'Olen': 'I have lived',
    'asunut': 'lived',
    'täällä': 'here',
    'kaksi': 'two',
    'vuotta': 'years',
    'Mennään': 'Let’s go',
    'kotiin': 'home',
    'Haluan': 'I want',
    'nähdä': 'to see',
    'Tule': 'Come',
    'heti': 'immediately',
    'tänne': 'here',
    'En': 'I cannot',
    'elää': 'live',
    'ilman': 'without',
    'sinua': 'you',
    'Nämä': 'These',
    'ovat': 'are',
    'hyviä': 'good',
    'Haluatko': 'Do you want',
    'kahvia': 'coffee',
    'Haluan': 'I want',
    'mennä': 'to go',
    'sinne': 'there',
    'Saat': 'You get',
    'palkinnon': 'a prize',
    'Te': 'You (plural)',
    'ette': 'do not',
    'tiedä': 'know',
    'Mitä': 'What',
    'haluat': 'do you want',
    'sanoa': 'to say',
    'Mitä': 'What',
    'tapahtui': 'happened',
    'eilen': 'yesterday',
    'Hän': 'He',
    'tulee': 'comes',
    'varmasti': 'surely',
    'Nämä': 'These',
    'ovat': 'are',
    'asiat': 'things',
    'jotka': 'which',
    'haluan': 'I want',
    'Ota': 'Take',
    'tämä': 'this',
    'kirja': 'book',
    'Minulla': 'I have',
    'on': 'is',
    'kolme': 'three',
    'omenaa': 'apples',
    'Voitko': 'Can you',
    'antaa': 'give',
    'minulle': 'me',
    'kynän': 'a pen',
    'Laita': 'Put',
    'se': 'it',
    'tähän': 'to this',
    'Tiedätkö': 'Do you know',
    'vastauksen': 'the answer',
    'Odota': 'Wait',
    'hetki': 'moment',
    'Hän': 'He',
    'menee': 'goes',
    'kouluun': 'to school',
    'En': 'I do not',
    'tarvitse': 'need',
    'apua': 'help',
    'Odotan': 'I am waiting',
    'teitä': 'you',
    'täällä': 'here',
    'Hän': 'He',
    'haluaa': 'wants',
    'mennä': 'to go',
    'ulos': 'out',
    'Nähdään': 'See you',
    'pian': 'soon',
    'Haluan': 'I want',
    'kertoa': 'to tell',
    'sinulle': 'you',
    'jotain': 'something',
    'He': 'They',
    'näkivät': 'saw',
    'meidät': 'us',
    'En': 'I have not',
    'ole': 'not',
    'nähnyt': 'seen',
    'häntä': 'him/her',
    'Haluan': 'I want',
    'saada': 'to get',
    'uuden': 'new',
    'työn': 'job',
    'Lähdemme': 'We will leave',
    'täältä': 'from here',
    'huomenna': 'tomorrow',
    'Teen': 'I do',
    'sen': 'it',
    'huomenna': 'tomorrow',
    'Puhuin': 'I talked',
    'hänestä': 'about him/her',
    'eilen': 'yesterday',
    'Poika': 'The boy',
    'pelaa': 'plays',
    'jalkapalloa': 'football',
    'Olen': 'I have',
    'tehnyt': 'done',
    'läksyt': 'homework',
    'Luojan': 'Thank',
    'kiitos': 'goodness',
    'Sanoin': 'I said',
    'sen': 'it',
    'eilen': 'yesterday',
    'Hän': 'He',
    'tekee': 'does',
    'sen': 'it',
    'hyvin': 'well',
    'Mene': 'Go',
    'sisään': 'inside',
    'Haluan': 'I want',
    'enemmän': 'more',
    'kahvia': 'coffee',
    'Olen': 'I am',
    'vastaan': 'against',
    'tätä': 'this',
    'suunnitelmaa': 'plan',
    'Usko': 'Believe',
    'minua': 'me',
    'Näin': 'I saw',
    'heidät': 'them',
    'eilen': 'yesterday',
    'Hän': 'He',
    'käy': 'visits',
    'täällä': 'here',
    'usein': 'often',
    'Se': 'It',
    'on': 'is',
    'tuolla': 'over there',
    'Tämä': 'This',
    'on': 'is',
    'tärkeä': 'important',
    'asia': 'matter',
    'He': 'They',
    'auttoivat': 'helped',
    'heitä': 'them',
    'Hän': 'He',
    'kertoi': 'told',
    'meille': 'to us',
    'kaiken': 'everything',
    'Ota': 'Take',
    'hetki': 'a moment',
    'aikaa': 'time',
    'Talo': 'The house',
    'jonka': 'which',
    'näit': 'you saw',
    'on': 'is',
    'minun': 'mine',
    'Se': 'It',
    'on': 'is',
    'varmaan': 'probably',
    'totta': 'true',
    'Minulla': 'I have',
    'on': 'a',
    'viesti': 'message',
    'teille': 'for you',
    'Olitko': 'Were you',
    'siellä': 'there',
    'eilen': 'yesterday',
    'Myöhästyin': 'I was late',
    'liikenteen': 'because of',
    'takia': 'the traffic',
    'Sano': 'Say',
    'se': 'it',
    'uudestaan': 'again',
    'Sain': 'I got',
    'lahjan': 'a gift',
    'eilen': 'yesterday',
    'He': 'They',
    'olivat': 'were',
    'ystäviä': 'friends',
    'Luulin': 'I thought',
    'että': 'that',
    'tiesin': 'I knew',
    'vastauksen': 'the answer',
    'Tämä': 'This',
    'on': 'is',
    'hienoa': 'great',
    'En': 'I have never',
    'ole': 'never',
    'ikinä': 'ever',
    'nähnyt': 'seen',
    'tätä': 'this',
    'Voimme': 'We can',
    'mennä': 'go',
    'nyt': 'now',
    'Tiedätkö': 'Do you know',
    'missä': 'where',
    'se': 'it',
    'on': 'is',
    'Hän': 'He',
    'piti': 'had to',
    'lähteä': 'leave',
    'aikaisin': 'early',
    'Haluan': 'I want',
    'tuon': 'that',
    'kirjan': 'book',
    'Rakastan': 'I love',
    'sinua': 'you',
    'Oletko': 'Are you',
    'varma': 'sure',
    'Hän': 'He',
    'on': 'is',
    'kuollut': 'dead',
    'Joo': 'Yeah',
    'olen': 'I am',
    'samaa': 'same',
    'mieltä': 'opinion',
    'Tehdään': 'Let’s do',
    'tämä': 'this',
    'yhdessä': 'together',
    'Hän': 'He',
    'voisi': 'could',
    'auttaa': 'help',
    'meitä': 'us',
    'Haluan': 'I want',
    'ottaa': 'to take',
    'kuvan': 'a picture',
    'Kerran': 'Once',
    'viikossa': 'a week',
    'Mihin': 'Where',
    'olet': 'are',
    'menossa': 'going',
    'Tämä': 'This',
    'on': 'is',
    'mielenkiintoinen': 'interesting',
    'juttu': 'thing',
    'Tarvitsen': 'I need',
    'apua': 'help',
    'Haluan': 'I want',
    'lähteä': 'to leave',
    'nyt': 'now',
    'Minne': 'Where',
    'menet': 'are you going',
    'Olen': 'I am',
    'yhä': 'still',
    'täällä': 'here',
    'Ajan': 'I am driving',
    'autoa': 'a car',
    'Olet': 'You are',
    'oikeassa': 'right',
    'Olemme': 'We are',
    'yhtä': 'equal',
    'mieltä': 'opinion',
    'Olen': 'I am',
    'väsynyt': 'tired',
    'siksi': 'therefore',
    'menen': 'I will go',
    'nukkumaan': 'to sleep',
    'Tulen': 'I will come',
    'sinne': 'there',
    'huomenna': 'tomorrow',
    'Hyvää': 'Good',
    'päivää': 'day',
    'Rouva': 'Mrs.',
    'Virtanen': 'Virtanen',
    'Tyttö': 'The girl',
    'leikkii': 'is playing',
    'pihalla': 'in the yard',
    'Mitä': 'What',
    'täällä': 'here',
    'tapahtuu': 'is happening',
    'Pidä': 'Have',
    'hauskaa': 'fun',
    'Haluan': 'I want',
    'toisen': 'another',
    'kahvin': 'coffee',
    'Pidän': 'I like',
    'tästä': 'this',
    'kirjasta': 'book',
    'Silloin': 'Then',
    'oli': 'was',
    'kesä': 'summer',
    'Hän': 'He',
    'haluaa': 'wants',
    'tappaa': 'to kill',
    'aikaa': 'time',
    'Näin': 'I saw',
    'teidät': 'you (plural)',
    'eilen': 'yesterday',
    'Nainen': 'The woman',
    'osti': 'bought',
    'kukkia': 'flowers',
    'Oletko': 'Are you',
    'valmis': 'ready',
    'lähtemään': 'to leave',
    'Minulla': 'I have',
    'on': 'is',
    'rahaa': 'money',
    'Teillä': 'You have (plural)',
    'on': 'are',
    'kiire': 'in a hurry',
    'Kuinka': 'How',
    'kauan': 'long',
    'tämä': 'this',
    'kestää': 'take',
    'Ihmiset': 'People',
    'ovat': 'are',
    'ystävällisiä': 'friendly',
    'Hän': 'He',
    'teki': 'did',
    'sen': 'it',
    'hyvin': 'well',
    'En': 'I could not',
    'voinut': 'could',
    'auttaa': 'help',
    'häntä': 'him',
    'Olisin': 'I would have',
    'pitänyt': 'kept',
    'sen': 'it',
    'Joskus': 'Sometimes',
    'käyn': 'I visit',
    'täällä': 'here',
    'Tee': 'Do',
    'tämä': 'this',
    'ensin': 'first',
    'Olisin': 'I would be',
    'iloinen': 'happy',
    'Olen': 'I am',
    'yksin': 'alone',
    'kotona': 'at home',
    'Tule': 'Come',
    'tänne': 'here',
    'kulta': 'darling',
    'En': 'I do not',
    'tiedä': 'know',
    'enkä': 'and I do not',
    'halua': 'want',
    'tietää': 'to know',
    'Tohtori': 'The doctor',
    'auttaa': 'helps',
    'sinua': 'you',
    'Katso': 'Look',
    'tuota': 'at that',
    'taloa': 'house',
    'Lopeta': 'Stop',
    'tuo': 'that',
    'Haluatko': 'Do you want',
    'lisää': 'more',
    'kahvia': 'coffee',
    'Nähdään': 'See you',
    'huomenna': 'tomorrow',
    'Menen': 'I go',
    'nyt': 'now',
    'kotiin': 'home',
    'Tarvitsen': 'I need',
    'apua': 'help',
    'Hyvää': 'Good',
    'päivää': 'day',
    'Tänään': 'Today',
    'on': 'is',
    'kaunis': 'beautiful',
    'päivä': 'day',
    'Tällä': 'with this',
    'autolla': 'car',
    'menemme': 'we go',
    'Hän': 'He',
    'meni': 'went',
    'ulos': 'out',
    'Ota': 'Take',
    'pari': 'couple',
    'omenaa': 'apples',
    'Kyse': 'a matter',
    'on': 'is',
    'ajasta': 'time',
    'Olen': 'I have',
    'käynyt': 'been',
    'siellä': 'there',
    'monta': 'many',
    'kertaa': 'times',
    'Oliko': 'Was it',
    'hän': 'he',
    'kotona': 'at home',
    'Älkää': 'Don’t (plural)',
    'menkö': 'go',
    'sinne': 'there',
    'Se': 'It',
    'on': 'is',
    'tosi': 'true',
    'Nähdään': 'See you',
    'myöhemmin': 'later',
    'Tuntuu': 'feels',
    'hyvältä': 'good',
    'Hän': 'He',
    'sai': 'got',
    'lahjan': 'gift',
    'Nähdään': 'See you',
    'huomenna': 'tomorrow',
    'Haluan': 'I want',
    'tavata': 'to meet',
    'sinut': 'you',
    'Niinkö': 'Really',
    'ajattelet': 'you think',
    'Hän': 'He',
    'odottaa': 'waits',
    'bussia': 'bus',
    'Tämä': 'This',
    'on': 'is',
    'minun': 'my',
    'uusi': 'new',
    'talo': 'house',
    'Olen': 'I have',
    'saanut': 'received',
    'kirjeen': 'letter',
    'Teen': 'I do',
    'sen': 'it',
    'jotta': 'so that',
    'voin': 'I can',
    'auttaa': 'help',
    'Mitä': 'What',
    'sanoit': 'you said',
    'Milloin': 'When',
    'tulet': 'are you coming',
    'Olen': 'I am',
    'ainoa': 'only',
    'lapsi': 'child',
    'Saan': 'I get',
    'uuden': 'new',
    'työn': 'job',
    'Näin': 'I saw',
    'jonkun': 'someone',
    'ovella': 'at the door',
    'Tule': 'Come',
    'alas': 'down',
    'nyt': 'now',
    'Minäkin': 'Me too',
    'haluan': 'I want',
    'jäätelöä': 'ice cream',
    'Halusin': 'I wanted',
    'tulla': 'to come',
    'mukaan': 'along',
    'Otan': 'I will take',
    'yhden': 'one',
    'kahvin': 'coffee',
    'Hän': 'He',
    'on': 'is',
    'paras': 'best',
    'ystäväni': 'my friend',
    'Kyllä': 'Yes',
    'sir': 'sir',
    'Auto': 'The car',
    'vie': 'takes',
    'meidät': 'us',
    'perille': 'to the destination',
    'Mene': 'Go',
    'ylös': 'up',
    'Pelkäsin': 'I was afraid',
    'etten': 'that I do not',
    'löydä': 'find',
    'sitä': 'it',
    'Tämä': 'This',
    'on': 'is',
    'parempi': 'better',
    'vaihtoehto': 'option',
    'Tämä': 'This',
    'kuuluu': 'belongs',
    'minulle': 'to me',
    'Hän': 'He',
    'osaa': 'knows',
    'puhua': 'to speak',
    'suomea': 'Finnish',
    'Meillä': 'We have',
    'on': 'an',
    'tärkeää': 'important',
    'asiaa': 'matter',
    'Mikään': 'Nothing',
    'ei': 'does not',
    'toimi': 'work',
    'Olen': 'I am',
    'silti': 'still',
    'iloinen': 'happy',
    'Okei': 'Okay',
    'tehdään': 'let’s do',
    'niin': 'that',
    'Haluan': 'I want',
    'jotakin': 'something',
    'syötävää': 'to eat',
    'Tämä': 'This',
    'on': 'is',
    'kaunis': 'beautiful',
    'paikka': 'place',
    'En': 'I did not',
    'nähnyt': 'see',
    'ketään': 'anyone',
    'Viime': 'Last',
    'viikolla': 'week',
    'olin': 'was',
    'lomalla': 'on vacation',
    'Ajattelin': 'I thought',
    'häntä': 'of him',
    'eilen': 'yesterday',
    'Se': 'She',
    'on': 'is',
    'nainen': 'woman',
    'jota': 'whom',
    'rakastan': 'I love',
    'Miehen': 'The man’s',
    'nimi': 'name',
    'on': 'is',
    'Matti': 'Matti',
    'Täällä': 'Here',
    'on': 'are',
    'paljon': 'many',
    'ihmisiä': 'people',
    'Haluan': 'I want',
    'alkaa': 'to start',
    'nyt': 'now',
    'Tein': 'I did',
    'sen': 'it',
    'eilen': 'yesterday',
    'En': 'I do not',
    'ymmärrä': 'understand',
    'tätä': 'this',
    'Mitä': 'What',
    'teit': 'did you do',
    'eilen': 'yesterday',
    'Haluan': 'I want',
    'hieman': 'a little',
    'sokeria': 'sugar',
    'Oletteko': 'Are you (plural)',
    'valmiit': 'ready',
    'Odota': 'Wait',
    'hetki': 'a moment',
    'Kuuntele': 'Listen',
    'musiikkia': 'to the music',
    'Muista': 'Remember',
    'ottaa': 'to take',
    'avaimet': 'keys',
    'Koe': 'The test',
    'on': 'is',
    'ohi': 'over',
    'Tämä': 'This',
    'on': 'is',
    'pieni': 'small',
    'talo': 'house',
    'Hän': 'He',
    'hyppäsi': 'jumped',
    'aidan': 'the fence',
    'yli': 'over',
    'Ymmärrän': 'I understand',
    'sinua': 'you',
    'Hän': 'He',
    'on': 'has',
    'tullut': 'come',
    'kotiin': 'home',
    'Meillä': 'We have',
    'on': 'the',
    'sama': 'same',
    'ongelma': 'problem',
    'Tämä': 'This',
    'on': 'is',
    'oikea': 'right',
    'vastaus': 'answer',
    'Yritän': 'I try',
    'parhaani': 'my best',
    'Hyvää': 'Good',
    'päivää': 'day',
    'neiti': 'miss',
    'Tämä': 'This',
    'riittää': 'is enough',
    'minulle': 'for me',
    'Tämä': 'This',
    'on': 'is',
    'vanha': 'old',
    'talo': 'house',
    'Minkä': 'Which',
    'kirjan': 'book',
    'haluat': 'do you want',
    'Luulen': 'I think',
    'että': 'that',
    'tiedän': 'I know',
    'vastauksen': 'the answer',
    'Saanko': 'May I get',
    'vettä': 'water',
    'Haluaisin': 'I would like',
    'kahvia': 'some coffee',
    'En': 'I didn’t',
    'tiennyt': 'know',
    'sitä': 'that',
    'Tulin': 'I came',
    'kotiin': 'home',
    'myöhään': 'late',
    'Toivottavasti': 'Hopefully',
    'sää': 'weather',
    'paranee': 'will improve',
    'Pyydän': 'I ask',
    'apua': 'for help',
    'Voisin': 'I could',
    'auttaa': 'help',
    'sinua': 'you',
    'Otan': 'I take',
    'yhden': 'one',
    'kahvin': 'coffee',
    'Haluan': 'I want',
    'soittaa': 'to call',
    'hänelle': 'him',
    'Haluan': 'I want',
    'puhua': 'to talk',
    'kanssasi': 'with you',
    'Tule': 'Come',
    'muuten': 'otherwise',
    'myöhästyt': 'you will be late',
    'Jokin': 'Something',
    'on': 'is',
    'vialla': 'wrong',
    'Isäni': 'My father',
    'on': 'is',
    'kotona': 'at home',
    'Teemme': 'We will do',
    'sen': 'it',
    'yhdessä': 'together',
    'Voinko': 'Can I',
    'auttaa': 'help',
    'sinua': 'you',
    'Hän': 'He',
    'kuoli': 'died',
    'eilen': 'yesterday',
    'Mitä': 'What',
    'tämä': 'this',
    'tarkoittaa': 'mean',
    'Tee': 'Do',
    'se': 'it',
    'nopeasti': 'quickly',
    'Meillä': 'We have',
    'on': 'many',
    'paljon': 'many',
    'asioita': 'things',
    'tehtävänä': 'to do',
    'Tulkaa': 'Come (plural)',
    'sisään': 'inside',
    'Puhu': 'Speak',
    'minulle': 'to me',
    'Kerro': 'Tell',
    'minuun': 'to me',
    'Olen': 'I’ve had',
    'saanut': 'had',
    'tarpeeksi': 'enough',
    'Ota': 'Take',
    'kätesi': 'your hand',
    'irti': 'off',
    'Kävele': 'Walk',
    'oven': 'the door',
    'läpi': 'through',
    'Tämä': 'This',
    'maistuu': 'tastes',
    'hyvältä': 'good',
    'Tulen': 'I will come',
    'kohta': 'soon',
    'Hän': 'He',
    'on': 'is',
    'poissa': 'away',
    'tänään': 'today',
    'Tämä': 'This',
    'on': 'is',
    'iso': 'big',
    'talo': 'house',
    'Minulla': 'I have',
    'on': 'a lot of',
    'paljon': 'a lot of',
    'töitä': 'work',
    'Tulin': 'I arrived',
    'vasta': 'just',
    'nyt': 'now',
    'Ole': 'Be',
    'kiltti': 'kind',
    'ja': 'and',
    'auta': 'help',
    'minua': 'me',
    'Mikä': 'What',
    'sinun': 'your',
    'nimesi': 'name',
    'on': 'is',
    'Olen': 'I am',
    'täysin': 'completely',
    'samaa': 'same',
    'mieltä': 'opinion',
    'Odota': 'Wait',
    'kunnes': 'until',
    'palaan': 'I return',
    'Puhu': 'Speak',
    'hiljaa': 'quietly',
    'ole': 'be',
    'kiltti': 'kind',
    'Poliisi': 'The police',
    'saapui': 'arrived',
    'nopeasti': 'quickly',
    'Minulla': 'I have',
    'on': 'is',
    'viisi': 'five',
    'kirjaa': 'books',
    'Talo': 'The house',
    'jossa': 'in which',
    'asun': 'I live',
    'on': 'is',
    'kaunis': 'beautiful',
    'Olisit': 'You would',
    'voinut': 'have been able',
    'auttaa': 'to help',
    'Olisin': 'I would have',
    'halunnut': 'wanted',
    'nähdä': 'to see',
    'sen': 'it',
    'Annoin': 'I gave',
    'kirjan': 'the book',
    'heille': 'to them',
    'Voit': 'You can',
    'valita': 'choose',
    'minkä': 'any',
    'tahansa': 'any',
    'Odota': 'Wait',
    'tähän': 'until',
    'asti': 'this point',
    'Pelkäsin': 'I was afraid',
    'ettet': 'that you would not',
    'tule': 'come',
    'Tämä': 'This',
    'on': 'is',
    'kaunis': 'beautiful',
    'päivä': 'day',
    'Senkin': 'You',
    'hölmö': 'fool',
    'Olen': 'I am',
    'tulossa': 'coming',
    'kotiin': 'home',
    'Haluan': 'I want',
    'löytää': 'to find',
    'ratkaisun': 'a solution',
    'Missä': 'Where',
    'isäsi': 'your father',
    'on': 'is',
    'Osaatko': 'Do you know',
    'käyttää': 'how to use',
    'tätä': 'this',
    'konetta': 'machine',
    'Se': 'It',
    'on': 'is',
    'kuitenkin': 'however',
    'totta': 'true',
    'Oletko': 'Are you',
    'oikeasti': 'really',
    'vakavissasi': 'serious',
    'Vuoden': 'The year',
    '2023': '2023',
    'talvi': 'winter',
    'oli': 'was',
    'kylmä': 'cold',
    'Ainakin': 'At least',
    'hän': 'he',
    'yritti': 'tried',
    'Ota': 'Take',
    'minut': 'me',
    'mukaan': 'with you',
    'Minulla': 'I don’t have',
    'ei': 'not',
    'ole': 'have',
    'rahaa': 'money',
    'Se': 'It',
    'kuulostaa': 'sounds like',
    'hyvältä': 'good',
    'Miltä': 'How',
    'se': 'it',
    'tuntuu': 'feels',
    'Minun': 'I must',
    'on': 'is',
    'pakko': 'must',
    'mennä': 'to go',
    'Haluan': 'I want',
    'yrittää': 'to try',
    'uudelleen': 'again',
    'En': 'I have never',
    'ole': 'not',
    'nähnyt': 'seen',
    'mitään': 'anything',
    'sellaista': 'such',
    'Se': 'It',
    'oli': 'was',
    'kiva': 'nice',
    'yllätys': 'surprise',
    'Olemme': 'We are',
    'samaa': 'the same',
    'mieltä': 'opinion',
    'Se': 'It',
    'maksaa': 'costs',
    'viisikymmentä': 'fifty',
    'dollaria': 'dollars',
    'Minulla': 'I have',
    'on': 'have',
    'neljä': 'four',
    'lasta': 'children',
    'Kello': 'The clock',
    'on': 'is',
    'viisi': 'five',
    'Pysy': 'Stay',
    'siinä': 'there',
    'Tämä': 'This',
    'on': 'is',
    'ihan': 'quite',
    'paska': 'crappy',
    'tilanne': 'situation',
    'Hän': 'He',
    'on': 'is',
    'ensimmäinen': 'first',
    'asiakas': 'customer',
    'Hän': 'He',
    'on': 'is',
    'hyvä': 'good',
    'kaveri': 'friend',
    'Ilma': 'The weather',
    'on': 'is',
    'mukava': 'pleasant',
    'Hän': 'He',
    'sanoo': 'says',
    'sen': 'it',
    'usein': 'often',
    'Olen': 'I am',
    'kotona': 'at home',
    'Tunnen': 'I feel',
    'oloni': 'myself',
    'hyväksi': 'good',
    'Mitä': 'What',
    'tarkoitat': 'do you mean',
    'Tämä': 'This',
    'on': 'is',
    'liikaa': 'too much',
    'Hitto': 'Damn',
    'unohdin': 'I forgot',
    'sen': 'it',
    'Kuulin': 'I heard',
    'sen': 'it',
    'uutisista': 'on the news',
    'Mitä': 'What',
    'mieltä': 'opinion',
    'olet': 'are you',
    'Olen': 'I am',
    'melkein': 'almost',
    'valmis': 'ready',
    'Näytä': 'Show',
    'minulle': 'me',
    'Puhutaan': 'We’ll talk',
    'niistä': 'about them',
    'myöhemmin': 'later',
    'Kerron': 'I will tell',
    'sinulle': 'you',
    'huomenna': 'tomorrow',
    'Oletko': 'Have you',
    'kuullut': 'heard',
    'sen': 'it',
    'Näin': 'I saw',
    'hänet': 'him',
    'eilen': 'yesterday',
    'Tämä': 'This',
    'on': 'is',
    'sinua': 'for you',
    'varten': 'for',
    'Se': 'It',
    'oli': 'was',
    'hieno': 'fine',
    'kokemus': 'experience',
    'Muut': 'The others',
    'ovat': 'are',
    'jo': 'already',
    'täällä': 'here',
    'Minulla': 'I have',
    'on': 'a',
    'hyvä': 'good',
    'tunne': 'feeling',
    'tästä': 'about this',
    'Tuntuu': 'It feels',
    'siltä': 'like',
    'että': 'that',
    'tämä': 'this',
    'onnistuu': 'will work',
    'Mä': 'I (informal)',
    'menen': 'I’m going',
    'nyt': 'now',
    'Tämä': 'This',
    'on': 'is',
    'tärkeä': 'important',
    'asia': 'matter',
    'Saitko': 'Did you get',
    'kirjeen': 'the letter',
    'Haluan': 'I want',
    'kuulla': 'to hear',
    'sen': 'it',
    'Näen': 'I will see',
    'sinut': 'you',
    'huomenna': 'tomorrow',
    'Mitä': 'What',
    'ajattelet': 'do you think',
    'meistä': 'about us',
    'Olen': 'I have',
    'kertonut': 'told',
    'sen': 'it',
    'sinulle': 'you',
    'Hän': 'He',
    'on': 'is',
    'eliittiä': 'an elite',
    'Luuletko': 'Do you think',
    'niin': 'so',
    'Kapteeni': 'The captain',
    'johtaa': 'leads',
    'alusta': 'the ship',
    'John': 'John',
    'on': 'is',
    'ystäväni': 'my friend',
    'Tänä': 'This',
    'iltana': 'evening',
    'menemme': 'we are going',
    'ulos': 'out',
    'En': 'I am not',
    'pysty': 'able',
    'tekemään': 'to do',
    'sitä': 'it',
    'Oli': 'It was',
    'hauska': 'fun',
    'ilta': 'evening',
    'Haloo': 'Hello',
    'oletko': 'are you',
    'siellä': 'there',
    'Hän': 'He',
    'kertoi': 'told',
    'minulle': 'me',
    'uutiset': 'the news',
    'Haluan': 'I want',
    'toisen': 'another',
    'mahdollisuuden': 'chance',
    'Jumala': 'God',
    'on': 'is',
    'suuri': 'great',
    'Tehdään': 'Let’s do',
    'se': 'it',
    'yhdessä': 'together',
    'Tule': 'Come',
    'kanssani': 'with me',
    'Auta': 'Help',
    'minua': 'me',
    'ole': 'be',
    'kiltti': 'kind',
    'Luuletko': 'Do you think',
    'että': 'that',
    'se': 'it',
    'toimii': 'will work',
    'Pikkuveli': 'Little brother',
    'on': 'is',
    'hauska': 'funny',
    'Jopa': 'Even',
    'hän': 'he',
    'tuli': 'came',
    'juhliin': 'to the party',
    'Näin': 'I saw',
    'sen': 'it',
    'sieltä': 'from there',
    'Näytät': 'You look',
    'väsyneeltä': 'tired',
    'Kaikki': 'Everyone',
    'tulivat': 'came',
    'paitsi': 'except',
    'hän': 'him',
    'Nuokin': 'Those',
    'ovat': 'are',
    'minun': 'mine',
    'Puhut': 'You speak',
    'hyvin': 'well',
    'suomea': 'Finnish',
    'Haluan': 'I want',
    'uskoa': 'to believe',
    'sinua': 'you',
    'Missä': 'Where',
    'äitisi': 'your mother',
    'on': 'is',
    'Mene': 'Go',
    'suoraan': 'directly',
    'kotiin': 'home',
    'Voitteko': 'Can you',
    'auttaa': 'help',
    'meitä': 'us',
    'Olimme': 'We were',
    'siellä': 'there',
    'eilen': 'yesterday',
    'Olen': 'I am',
    'hänen': 'with him/her',
    'kanssaan': 'with him/her',
    'Mikset': 'Why don’t you',
    'sano': 'say',
    'sitä': 'it'
};
